# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "weekly"
    groups:
      aggrid:
        patterns:
          - "ag-grid*"
      react:
        patterns:
          - "react*"
    ignore:
      # @types/vscode should match the engine version we're using
      # should not be upgraded on its own
      - dependency-name: "@types/vscode"
  - package-ecosystem: "npm"
    directory: "/server"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/website"
    schedule:
      interval: "weekly"
    groups:
      docusaurus:
        patterns:
          - "@docusaurus/*"
      react:
        patterns:
          - "react*"
  - package-ecosystem: "github-actions"
    # Don't need to specify `/.github/workflows` for `directory`. Github knows it.
    directory: "/"
    schedule:
      interval: "weekly"
