name: Bug Report
description: Report a bug
type: Bug
body:
  - type: textarea
    attributes:
      label: Describe the bug
      placeholder: A clear and concise description of what the bug is
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Detailed steps for us to consistently reproduce what you're seeing
      value: |
        1. 
        2.
  - type: textarea
    attributes:
      label: SAS code (if applicable)
      description: If applicable, add the minimal SAS code that will reproduce the bug
      render: SAS
  - type: textarea
    attributes:
      label: Expected behavior
      placeholder: A clear and concise description of what you expected to happen
  - type: textarea
    attributes:
      label: Screenshots
      placeholder: If applicable, add screenshots to help explain your problem
  - type: input
    attributes:
      label: Client OS
      description: Where is your VS Code running on?
      placeholder: e.g. Windows 11
  - type: input
    attributes:
      label: Extension version
      placeholder: e.g. v1.13.0
    validations:
      required: true
  - type: input
    attributes:
      label: SAS version
      placeholder: e.g. Viya 2024.09
  - type: textarea
    attributes:
      label: Additional context
      placeholder: Add any other context about the problem here
