// Copyright © 2024, SAS Institute Inc., Cary, NC, USA.  All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0
import { LogLine } from "../../../src/connection";

export const logWith13Problems: LogLine[] = [
  {
    line: "28   /** LOG_START_INDICATOR **/",
    type: "source",
    version: 1,
  },
  { line: "29   title;footnote;ods _all_ close;", type: "source", version: 1 },
  { line: "30   ods graphics on;", type: "source", version: 1 },
  {
    line: "31   ods html5 style=Illuminate options(bitmap_mode='inline' svg_mode='inline');",
    type: "source",
    version: 1,
  },
  {
    line: "NOTE: Writing HTML5 Body file: sashtml2.htm",
    type: "note",
    version: 1,
  },
  {
    line: "32   %let _SASPROGRAMFILE = %nrquote(%nrstr(c:\\\\SAS\\\\GIT\\\\GitHub\\\\TestData\\\\error3.sas));",
    type: "source",
    version: 1,
  },
  { line: "33   ", type: "source", version: 1 },
  { line: "34   ", type: "source", version: 1 },
  { line: "35   ", type: "source", version: 1 },
  { line: "36   /* I am comment */", type: "source", version: 1 },
  { line: "37   options ls=72;", type: "source", version: 1 },
  { line: "38   data pf70 pm70 pf80 pm80;", type: "source", version: 1 },
  {
    line: "39   \\tinput state $ pop_f70 pop_m70 pop_f80 pop_m80 @@;",
    type: "source",
    version: 1,
  },
  {
    line: "40   \\tdrop pop_m70 pop_f70 pop_m80 pop_f80;",
    type: "source",
    version: 1,
  },
  { line: "41   \\tdecade= 70;", type: "source", version: 1 },
  { line: "42   \\tsex= 'Female'", type: "source", version: 1 },
  { line: "43   \\tpop= pop_f70;  output pf70;", type: "source", version: 1 },
  { line: "      ---", type: "error", version: 1 },
  { line: "      22", type: "error", version: 1 },
  {
    line: "ERROR 22-322: Syntax error, expecting one of the following: !, !!, &, ",
    type: "error",
    version: 1,
  },
  {
    line: "              *, **, +, -, /, ;, <, <=, <>, =, >, ><, >=, AND, EQ, GE, ",
    type: "error",
    version: 1,
  },
  {
    line: "              GT, IN, LE, LT, MAX, MIN, NE, NG, NL, NOTIN, OR, ^=, |, ",
    type: "error",
    version: 1,
  },
  { line: "              ||, ~=.  ", type: "error", version: 1 },
  { line: "", type: "normal", version: 1 },
  { line: "44   \\tsex= 'Male';", type: "source", version: 1 },
  { line: "45   \\tpop= pop_m70;  output pm70;", type: "source", version: 1 },
  { line: "46   \\tdecade= 80;", type: "source", version: 1 },
  { line: "47   \\tpop= pop_m80;  output pm80;", type: "source", version: 1 },
  { line: "48   \\tsex= 'Female';", type: "source", version: 1 },
  { line: "49   \\tpop= pop_f80;  output pf80;", type: "source", version: 1 },
  { line: "50   \\tcards,", type: "source", version: 1 },
  { line: "           -", type: "error", version: 1 },
  { line: "           22", type: "error", version: 1 },
  { line: "           76", type: "error", version: 1 },
  {
    line: "ERROR 22-322: Syntax error, expecting one of the following: ;, CANCEL, ",
    type: "error",
    version: 1,
  },
  { line: "              PGM.  ", type: "error", version: 1 },
  { line: "", type: "normal", version: 1 },
  {
    line: "ERROR 76-322: Syntax error, statement will be ignored.",
    type: "error",
    version: 1,
  },
  { line: "", type: "normal", version: 1 },
  {
    line: "51   ALA    1.78  1.66  2.02  1.87   ALASKA 0.14  0.16  0.19  0.21",
    type: "source",
    version: 1,
  },
  {
    line: "52   ARIZ   0.90  0.87  1.38  1.34   ARK    0.99  0.93  1.18  1.10",
    type: "source",
    version: 1,
  },
  {
    line: "53   CALIF 10.14  9.82 12.00 11.67   COLO   1.12  1.09  1.46  1.43",
    type: "source",
    version: 1,
  },
  {
    line: "54   CONN   1.56  1.47  1.61  1.50   DEL    0.28  0.27  0.31  0.29",
    type: "source",
    version: 1,
  },
  {
    line: "55   FLA    3.51  3.28  5.07  4.68   GA     2.36  2.23  2.82  2.64",
    type: "source",
    version: 1,
  },
  {
    line: "56   HAW    0.37  0.40  0.47  0.49   IDAHO  0.36  0.36  0.47  0.47",
    type: "source",
    version: 1,
  },
  {
    line: "57   ILL    5.72  5.39  5.89  5.54   IND    2.66  2.53  2.82  2.67",
    type: "source",
    version: 1,
  },
  {
    line: "58   IOWA   1.45  1.37  1.50  1.41   KAN    1.15  1.02  1.21  1.16",
    type: "source",
    version: 1,
  },
  {
    line: "59   KY     1.64  1.58  1.87  1.79   LA     1.87  1.77  2.17  2.04",
    type: "source",
    version: 1,
  },
  {
    line: "60   ME     0.51  0.48  0.58  0.55   MD     2.01  1.92  2.17  2.04",
    type: "source",
    version: 1,
  },
  {
    line: "61   MASS   2.97  2.72  3.01  2.73   MICH   4.53  4.39  4.75  4.52",
    type: "source",
    version: 1,
  },
  {
    line: "62   MINN   1.94  1.86  2.08  2.00   MISS   1.14  1.07  1.31  1.21",
    type: "source",
    version: 1,
  },
  {
    line: "63   MO     2.42  2.26  2.55  2.37   MONT   0.35  0.35  0.39  0.39",
    type: "source",
    version: 1,
  },
  {
    line: "64   NEB    0.76  0.72  0.80  0.77   NEV    0.24  0.25  0.40  0.41",
    type: "source",
    version: 1,
  },
  {
    line: "65   NH     0.38  0.36  0.47  0.45   NJ     3.70  3.47  3.83  3.53",
    type: "source",
    version: 1,
  },
  {
    line: "4                            The SAS System",
    type: "title",
    version: 1,
  },
  {
    line: "                                    Friday, January 19, 2024 08:12:00 AM",
    type: "title",
    version: 1,
  },
  { line: "", type: "title", version: 1 },
  {
    line: "66   NM     0.52  0.50  0.66  0.64   NY     9.52  8.72  9.22  8.34",
    type: "source",
    version: 1,
  },
  {
    line: "67   NC     2.59  2.49  3.03  2.86   ND     0.31  0.31  0.32  0.33",
    type: "source",
    version: 1,
  },
  {
    line: "68   OHIO   5.49  5.16  5.58  5.22   OKLA   1.31  1.25  1.55  1.48",
    type: "source",
    version: 1,
  },
  {
    line: "69   ORE    1.07  1.02  1.34  1.30   PA     6.13  5.67  6.18  5.68",
    type: "source",
    version: 1,
  },
  {
    line: "70   RI     0.48  0.46  0.50  0.45   SC     1.32  1.27  1.60  1.52",
    type: "source",
    version: 1,
  },
  {
    line: "71   SD     0.34  0.33  0.35  0.34   TENN   2.03  1.90  2.37  2.22",
    type: "source",
    version: 1,
  },
  {
    line: "72   TEXAS  5.72  5.48  7.23  7.00   UTAH   0.54  0.52  0.74  0.72",
    type: "source",
    version: 1,
  },
  {
    line: "73   VT     0.23  0.22  0.26  0.25   VA     2.35  2.30  2.73  2.62",
    type: "source",
    version: 1,
  },
  {
    line: "NOTE: DATA statement used (Total process time):",
    type: "note",
    version: 1,
  },
  { line: "      real time           0.01 seconds", type: "note", version: 1 },
  { line: "      cpu time            0.02 seconds", type: "note", version: 1 },
  { line: "      ", type: "note", version: 1 },
  {
    line: "NOTE: Character values have been converted to numeric ",
    type: "note",
    version: 1,
  },
  {
    line: "      values at the places given by: (Line):(Column).",
    type: "note",
    version: 1,
  },
  { line: "      42:7   44:7   48:7   ", type: "note", version: 1 },
  {
    line: "NOTE: The SAS System stopped processing this step because of errors.",
    type: "note",
    version: 1,
  },
  {
    line: "WARNING: The data set WORK.PF70 may be incomplete.  When this step was ",
    type: "warning",
    version: 1,
  },
  {
    line: "         stopped there were 0 observations and 4 variables.",
    type: "warning",
    version: 1,
  },
  {
    line: "WARNING: The data set WORK.PM70 may be incomplete.  When this step was ",
    type: "warning",
    version: 1,
  },
  {
    line: "         stopped there were 0 observations and 4 variables.",
    type: "warning",
    version: 1,
  },
  {
    line: "WARNING: The data set WORK.PF80 may be incomplete.  When this step was ",
    type: "warning",
    version: 1,
  },
  {
    line: "         stopped there were 0 observations and 4 variables.",
    type: "warning",
    version: 1,
  },
  {
    line: "WARNING: The data set WORK.PM80 may be incomplete.  When this step was ",
    type: "warning",
    version: 1,
  },
  {
    line: "         stopped there were 0 observations and 4 variables.",
    type: "warning",
    version: 1,
  },
  {
    line: "74   WASH   1.72  1.69  2.08  2.05   W.VA   0.90  0.84  1.00  0.95",
    type: "source",
    version: 1,
  },
  {
    line: "75   WIS    2.25  2.17  2.40  2.31   WYO    0.16  0.17  0.23  0.24",
    type: "source",
    version: 1,
  },
  {
    line: "76   XX      .     .     .     .     YY      .     .     .     .",
    type: "source",
    version: 1,
  },
  { line: "77   ;", type: "source", version: 1 },
  { line: "", type: "note", version: 1 },
  { line: "", type: "note", version: 1 },
  { line: "78   data popstate;", type: "source", version: 1 },
  { line: "79   \\tset pf70 pm70 pf80 pm80;", type: "source", version: 1 },
  {
    line: "80   \\tlabel pop= 'Census Population In Millions';",
    type: "source",
    version: 1,
  },
  { line: "81   title 'The SAS System';", type: "source", version: 1 },
  { line: "", type: "note", version: 1 },
  {
    line: "NOTE: The data set WORK.POPSTATE has 0 observations and 4 variables.",
    type: "note",
    version: 1,
  },
  {
    line: "NOTE: DATA statement used (Total process time):",
    type: "note",
    version: 1,
  },
  { line: "      real time           0.00 seconds", type: "note", version: 1 },
  { line: "      cpu time            0.00 seconds", type: "note", version: 1 },
  { line: "      ", type: "note", version: 1 },
  { line: "", type: "note", version: 1 },
  {
    line: "82   proc univariate data=popstate freq plot normal;",
    type: "source",
    version: 1,
  },
  { line: "83   \\tvar2 pop;", type: "source", version: 1 },
  { line: "      ----", type: "warning", version: 1 },
  { line: "      1", type: "warning", version: 1 },
  {
    line: "WARNING 1-322: Assuming the symbol VAR was misspelled as var2.",
    type: "warning",
    version: 1,
  },
  { line: "84   \\tid state;", type: "source", version: 1 },
  { line: "85   \\tby decade sex;", type: "source", version: 1 },
  {
    line: "86   \\toutput out= univout mean= popnmean median= popn50",
    type: "source",
    version: 1,
  },
  {
    line: "87   \\t\\tpctlpre= pop_  pctlpts= 50, 95 to 100 by 2.5;",
    type: "source",
    version: 1,
  },
  { line: "", type: "note", version: 1 },
  {
    line: "NOTE: The data set WORK.UNIVOUT has 0 observations and 0 variables.",
    type: "note",
    version: 1,
  },
  {
    line: "NOTE: PROCEDURE UNIVARIATE used (Total process time):",
    type: "note",
    version: 1,
  },
  { line: "      real time           0.01 seconds", type: "note", version: 1 },
  { line: "      cpu time            0.00 seconds", type: "note", version: 1 },
  { line: "      ", type: "note", version: 1 },
  { line: "", type: "note", version: 1 },
  {
    line: "5                            The SAS System",
    type: "title",
    version: 1,
  },
  {
    line: "                                    Friday, January 19, 2024 08:12:00 AM",
    type: "title",
    version: 1,
  },
  { line: "", type: "title", version: 1 },
  { line: "88   proc print data= univout;", type: "source", version: 1 },
  {
    line: "89   \\ttitle 'Output Dataset From PROC UNIVARIATE';",
    type: "source",
    version: 1,
  },
  {
    line: "90   \\tformat popn50 pop_50 pop_95 pop_97_5 pop_100 best8.;",
    type: "source",
    version: 1,
  },
  {
    line: "WARNING: Variable POPN50 not found in data set WORK.UNIVOUT.",
    type: "warning",
    version: 1,
  },
  {
    line: "WARNING: Variable POP_50 not found in data set WORK.UNIVOUT.",
    type: "warning",
    version: 1,
  },
  {
    line: "WARNING: Variable POP_95 not found in data set WORK.UNIVOUT.",
    type: "warning",
    version: 1,
  },
  {
    line: "WARNING: Variable POP_97_5 not found in data set WORK.UNIVOUT.",
    type: "warning",
    version: 1,
  },
  {
    line: "WARNING: Variable POP_100 not found in data set WORK.UNIVOUT.",
    type: "warning",
    version: 1,
  },
  { line: "91   ", type: "source", version: 1 },
  { line: "92   ;*';*\\\";*/;run;", type: "source", version: 1 },
  { line: "", type: "note", version: 1 },
  {
    line: "NOTE: PROCEDURE PRINT used (Total process time):",
    type: "note",
    version: 1,
  },
  { line: "      real time           0.01 seconds", type: "note", version: 1 },
  { line: "      cpu time            0.00 seconds", type: "note", version: 1 },
  { line: "      ", type: "note", version: 1 },
  { line: "", type: "note", version: 1 },
  {
    line: "92 !               quit;ods html5 close;",
    type: "source",
    version: 1,
  },
];

export const logWith7Problems: LogLine[] = [
  {
    line: "28   /** LOG_START_INDICATOR **/",
    type: "source",
    version: 1,
  },
  { line: "29   title;footnote;ods _all_ close;", type: "source", version: 1 },
  { line: "30   ods graphics on;", type: "source", version: 1 },
  {
    line: "31   ods html5 style=Ignite options(bitmap_mode='inline' svg_mode='inline');",
    type: "source",
    version: 1,
  },
  {
    line: "NOTE: Writing HTML5 Body file: sashtml2.htm",
    type: "note",
    version: 1,
  },
  {
    line: "32   %let _SASPROGRAMFILE = %nrquote(%nrstr(c:\\\\SAS\\\\GIT\\\\GitHub\\\\TestData\\\\error4.sas));",
    type: "source",
    version: 1,
  },
  { line: "33   proc foo; run;", type: "source", version: 1 },
  { line: "ERROR: Procedure FOO not found.", type: "error", version: 1 },
  { line: "", type: "note", version: 1 },
  {
    line: "NOTE: The SAS System stopped processing this step because of errors.",
    type: "note",
    version: 1,
  },
  {
    line: "NOTE: PROCEDURE FOO used (Total process time):",
    type: "note",
    version: 1,
  },
  { line: "      real time           0.00 seconds", type: "note", version: 1 },
  { line: "      cpu time            0.00 seconds", type: "note", version: 1 },
  { line: "      ", type: "note", version: 1 },
  { line: "34   ", type: "source", version: 1 },
  { line: "35   options option=foo;", type: "source", version: 1 },
  { line: "             ------", type: "error", version: 1 },
  { line: "             13", type: "error", version: 1 },
  {
    line: "ERROR 13-12: Unrecognized SAS option name OPTION.",
    type: "error",
    version: 1,
  },
  { line: "36   ", type: "source", version: 1 },
  { line: "", type: "note", version: 1 },
  { line: "", type: "note", version: 1 },
  { line: "37   data x;", type: "source", version: 1 },
  { line: "38   ", type: "source", version: 1 },
  { line: "39       print(x);", type: "source", version: 1 },
  { line: "                 -", type: "error", version: 1 },
  { line: "                 22", type: "error", version: 1 },
  { line: "                 76", type: "error", version: 1 },
  {
    line: "ERROR: Undeclared array referenced: print.",
    type: "error",
    version: 1,
  },
  {
    line: "ERROR 22-322: Syntax error, expecting one of the following: +, =.  ",
    type: "error",
    version: 1,
  },
  { line: "", type: "normal", version: 1 },
  {
    line: "ERROR 76-322: Syntax error, statement will be ignored.",
    type: "error",
    version: 1,
  },
  { line: "", type: "normal", version: 1 },
  { line: "40   ", type: "source", version: 1 },
  { line: "41   run;", type: "source", version: 1 },
  { line: "", type: "note", version: 1 },
  {
    line: "NOTE: The SAS System stopped processing this step because of errors.",
    type: "note",
    version: 1,
  },
  {
    line: "WARNING: The data set WORK.X may be incomplete.  When this step was stopped there were 0 observations and 1 variables.",
    type: "warning",
    version: 1,
  },
  {
    line: "WARNING: Data set WORK.X was not replaced because this step was stopped.",
    type: "warning",
    version: 1,
  },
  {
    line: "NOTE: DATA statement used (Total process time):",
    type: "note",
    version: 1,
  },
  { line: "      real time           0.00 seconds", type: "note", version: 1 },
  { line: "      cpu time            0.00 seconds", type: "note", version: 1 },
  { line: "      ", type: "note", version: 1 },
  { line: "", type: "note", version: 1 },
  {
    line: "42   ;*';*\\\";*/;run;quit;ods html5 close;",
    type: "source",
    version: 1,
  },
];

export const logWith3Problems: LogLine[] = [
  {
    line: "1                                                          The SAS System                       Monday, January 22, 2024 02:43:00 AM",
    type: "title",
    version: 1,
  },
  { line: "", type: "title", version: 1 },
  {
    line: "NOTE: Copyright (c) 2016-2023 by SAS Institute Inc., Cary, NC, USA. ",
    type: "note",
    version: 1,
  },
  {
    line: "NOTE: SAS (r) Proprietary Software V.04.00 (TS M0 MBCS3170) ",
    type: "note",
    version: 1,
  },
  {
    line: "      Licensed to SCI-VA-VIYA4CD-LAX-RELEASE-TESTREADY, Site 70180938.",
    type: "note",
    version: 1,
  },
  {
    line: "NOTE: This session is executing on the Linux 4.18.0-425.3.1.el8.x86_64 (LIN X64) platform.",
    type: "note",
    version: 1,
  },
  { line: "", type: "normal", version: 1 },
  { line: "", type: "normal", version: 1 },
  { line: "", type: "normal", version: 1 },
  { line: "NOTE: Additional host information:", type: "note", version: 1 },
  { line: "", type: "note", version: 1 },
  {
    line: " Linux LIN X64 4.18.0-425.3.1.el8.x86_64 #1 SMP Wed Nov 9 20:13:27 UTC 2022 x86_64 Red Hat Enterprise Linux release 8.9 (Ootpa) ",
    type: "note",
    version: 1,
  },
  { line: "", type: "note", version: 1 },
  { line: "NOTE: SAS initialization used:", type: "note", version: 1 },
  { line: "      real time           0.04 seconds", type: "note", version: 1 },
  { line: "      cpu time            0.04 seconds", type: "note", version: 1 },
  { line: "      ", type: "note", version: 1 },
  { line: "", type: "note", version: 1 },
  {
    line: "NOTE: AUTOEXEC processing beginning; file is /opt/sas/viya/config/etc/compsrv/default/autoexec.sas.",
    type: "note",
    version: 1,
  },
  { line: "", type: "normal", version: 1 },
  { line: "", type: "note", version: 1 },
  {
    line: "NOTE: DATA statement used (Total process time):",
    type: "note",
    version: 1,
  },
  { line: "      real time           0.01 seconds", type: "note", version: 1 },
  { line: "      cpu time            0.02 seconds", type: "note", version: 1 },
  { line: "      ", type: "note", version: 1 },
  { line: "", type: "note", version: 1 },
  { line: "", type: "note", version: 1 },
  { line: "", type: "normal", version: 1 },
  { line: "NOTE: AUTOEXEC processing completed.", type: "note", version: 1 },
  { line: "", type: "note", version: 1 },
  { line: "", type: "note", version: 1 },
  {
    line: "NOTE: The LOCKDOWN option has been set. SAS is now in the lockdown state.",
    type: "note",
    version: 1,
  },
  { line: "", type: "note", version: 1 },
  {
    line: "NOTE: NOTE: The LOCKDOWN option has been set. SAS is now in the lockdown state.",
    type: "note",
    version: 1,
  },
  {
    line: "1    /** LOG_START_INDICATOR **/",
    type: "source",
    version: 1,
  },
  { line: "2    title;footnote;ods _all_ close;", type: "source", version: 1 },
  { line: "3    ods graphics on;", type: "source", version: 1 },
  {
    line: "4    ods html5 style=Illuminate options(bitmap_mode='inline' svg_mode='inline');",
    type: "source",
    version: 1,
  },
  {
    line: "NOTE: Writing HTML5 Body file: sashtml.htm",
    type: "note",
    version: 1,
  },
  {
    line: "5    %let _SASPROGRAMFILE = %nrquote(%nrstr(c:\\\\SAS\\\\GIT\\\\GitHub\\\\TestData\\\\error5.sas));",
    type: "source",
    version: 1,
  },
  { line: "6    option ls=72,", type: "source", version: 1 },
  { line: "                 -", type: "error", version: 1 },
  { line: "                 13", type: "error", version: 1 },
  {
    line: "ERROR 13-12: Unrecognized SAS option name ,.",
    type: "error",
    version: 1,
  },
  { line: "", type: "normal", version: 1 },
  { line: "7    ", type: "source", version: 1 },
  { line: "8    data pf70;", type: "source", version: 1 },
  { line: "     ----", type: "error", version: 1 },
  { line: "     13", type: "error", version: 1 },
  {
    line: "ERROR 13-12: Unrecognized SAS option name DATA.",
    type: "error",
    version: 1,
  },
  { line: "", type: "error", version: 1 },
  { line: "8  ! data pf70;", type: "source", version: 1 },
  { line: "          ----", type: "error", version: 1 },
  { line: "          13", type: "error", version: 1 },
  {
    line: "ERROR 13-12: Unrecognized SAS option name PF70.",
    type: "error",
    version: 1,
  },
  { line: "", type: "normal", version: 1 },
  {
    line: "9    ;*';*\\\";*/;run;quit;ods html5 close;",
    type: "source",
    version: 1,
  },
];

export const replayedLogWith7Problems: LogLine[] = [
  {
    line: "1                                                          The SAS System                       Monday, January 22, 2024 05:24:00 AM",
    type: "title",
    version: 1,
  },
  { line: "", type: "title", version: 1 },
  {
    line: "NOTE: Copyright (c) 2016-2023 by SAS Institute Inc., Cary, NC, USA. ",
    type: "note",
    version: 1,
  },
  {
    line: "NOTE: SAS (r) Proprietary Software V.04.00 (TS M0 MBCS3170) ",
    type: "note",
    version: 1,
  },
  {
    line: "      Licensed to SCI-VA-VIYA4CD-LAX-RELEASE-TESTREADY, Site 70180938.",
    type: "note",
    version: 1,
  },
  {
    line: "NOTE: This session is executing on the Linux 4.18.0-425.3.1.el8.x86_64 (LIN X64) platform.",
    type: "note",
    version: 1,
  },
  { line: "", type: "normal", version: 1 },
  { line: "", type: "normal", version: 1 },
  { line: "", type: "normal", version: 1 },
  { line: "NOTE: Additional host information:", type: "note", version: 1 },
  { line: "", type: "note", version: 1 },
  {
    line: " Linux LIN X64 4.18.0-425.3.1.el8.x86_64 #1 SMP Wed Nov 9 20:13:27 UTC 2022 x86_64 Red Hat Enterprise Linux release 8.9 (Ootpa) ",
    type: "note",
    version: 1,
  },
  { line: "", type: "note", version: 1 },
  { line: "NOTE: SAS initialization used:", type: "note", version: 1 },
  { line: "      real time           0.04 seconds", type: "note", version: 1 },
  { line: "      cpu time            0.03 seconds", type: "note", version: 1 },
  { line: "      ", type: "note", version: 1 },
  { line: "", type: "note", version: 1 },
  {
    line: "NOTE: AUTOEXEC processing beginning; file is /opt/sas/viya/config/etc/compsrv/default/autoexec.sas.",
    type: "note",
    version: 1,
  },
  { line: "", type: "normal", version: 1 },
  { line: "", type: "note", version: 1 },
  {
    line: "NOTE: DATA statement used (Total process time):",
    type: "note",
    version: 1,
  },
  { line: "      real time           0.01 seconds", type: "note", version: 1 },
  { line: "      cpu time            0.00 seconds", type: "note", version: 1 },
  { line: "      ", type: "note", version: 1 },
  { line: "", type: "note", version: 1 },
  { line: "", type: "note", version: 1 },
  { line: "", type: "normal", version: 1 },
  { line: "NOTE: AUTOEXEC processing completed.", type: "note", version: 1 },
  { line: "", type: "note", version: 1 },
  { line: "", type: "note", version: 1 },
  {
    line: "NOTE: The LOCKDOWN option has been set. SAS is now in the lockdown state.",
    type: "note",
    version: 1,
  },
  { line: "", type: "note", version: 1 },
  {
    line: "NOTE: NOTE: The LOCKDOWN option has been set. SAS is now in the lockdown state.",
    type: "note",
    version: 1,
  },
  {
    line: "1    /** LOG_START_INDICATOR **/",
    type: "source",
    version: 1,
  },
  {
    line: "2    title;footnote;ods _all_ close;",
    type: "source",
    version: 1,
  },
  { line: "3    ods graphics on;", type: "source", version: 1 },
  {
    line: "4    ods html5 style=Illuminate options(bitmap_mode='inline' svg_mode='inline');",
    type: "source",
    version: 1,
  },
  {
    line: "NOTE: Writing HTML5 Body file: sashtml.htm",
    type: "note",
    version: 1,
  },
  {
    line: "5    %let _SASPROGRAMFILE = %nrquote(%nrstr(c:\\\\SAS\\\\GIT\\\\GitHub\\\\TestData\\\\error4.sas));",
    type: "source",
    version: 1,
  },
  { line: "6    proc foo; run;", type: "source", version: 1 },
  { line: "ERROR: Procedure FOO not found.", type: "error", version: 1 },
  { line: "", type: "note", version: 1 },
  {
    line: "NOTE: The SAS System stopped processing this step because of errors.",
    type: "note",
    version: 1,
  },
  {
    line: "NOTE: Due to ERROR(s) above, SAS set option OBS=0, enabling syntax check mode. ",
    type: "note",
    version: 1,
  },
  {
    line: "      This prevents execution of subsequent data modification statements.",
    type: "note",
    version: 1,
  },
  {
    line: "NOTE: PROCEDURE FOO used (Total process time):",
    type: "note",
    version: 1,
  },
  { line: "      real time           0.00 seconds", type: "note", version: 1 },
  { line: "      cpu time            0.00 seconds", type: "note", version: 1 },
  { line: "      ", type: "note", version: 1 },
  { line: "7    ", type: "source", version: 1 },
  { line: "8    options option=foo;", type: "source", version: 1 },
  { line: "             ------", type: "error", version: 1 },
  { line: "             13", type: "error", version: 1 },
  {
    line: "ERROR 13-12: Unrecognized SAS option name OPTION.",
    type: "error",
    version: 1,
  },
  { line: "9    ", type: "source", version: 1 },
  { line: "", type: "note", version: 1 },
  { line: "", type: "note", version: 1 },
  { line: "10   data x;", type: "source", version: 1 },
  { line: "11   ", type: "source", version: 1 },
  { line: "12       print(x);", type: "source", version: 1 },
  {
    line: "2                                                          The SAS System                       Monday, January 22, 2024 05:24:00 AM",
    type: "title",
    version: 1,
  },
  { line: "", type: "title", version: 1 },
  { line: "                 -", type: "error", version: 1 },
  { line: "                 22", type: "error", version: 1 },
  { line: "                 76", type: "error", version: 1 },
  {
    line: "ERROR: Undeclared array referenced: print.",
    type: "error",
    version: 1,
  },
  {
    line: "ERROR 22-322: Syntax error, expecting one of the following: +, =.  ",
    type: "error",
    version: 1,
  },
  { line: "", type: "normal", version: 1 },
  {
    line: "ERROR 76-322: Syntax error, statement will be ignored.",
    type: "error",
    version: 1,
  },
  { line: "", type: "normal", version: 1 },
  { line: "13   ", type: "source", version: 1 },
  { line: "14   run;", type: "source", version: 1 },
  { line: "", type: "note", version: 1 },
  {
    line: "NOTE: The SAS System stopped processing this step because of errors.",
    type: "note",
    version: 1,
  },
  {
    line: "WARNING: The data set WORK.X may be incomplete.  When this step was stopped there were 0 observations and 1 variables.",
    type: "warning",
    version: 1,
  },
  {
    line: "NOTE: DATA statement used (Total process time):",
    type: "note",
    version: 1,
  },
  { line: "      real time           0.00 seconds", type: "note", version: 1 },
  { line: "      cpu time            0.02 seconds", type: "note", version: 1 },
  { line: "      ", type: "note", version: 1 },
  { line: "", type: "note", version: 1 },
  {
    line: "15   ;*';*\\\";*/;run;quit;ods html5 close;",
    type: "source",
    version: 1,
  },
  { line: "16   title;footnote;ods _all_ close;", type: "source", version: 1 },
  { line: "17   ods graphics on;", type: "source", version: 1 },
  {
    line: "18   ods html5 style=Illuminate options(bitmap_mode='inline' svg_mode='inline');",
    type: "source",
    version: 1,
  },
  {
    line: "NOTE: Writing HTML5 Body file: sashtml1.htm",
    type: "note",
    version: 1,
  },
  {
    line: "19   %let _SASPROGRAMFILE = %nrquote(%nrstr(c:\\\\SAS\\\\GIT\\\\GitHub\\\\TestData\\\\error4.sas));",
    type: "source",
    version: 1,
  },
  { line: "20   ;", type: "source", version: 1 },
  {
    line: "21   ;*';*\\\";*/;run;quit;ods html5 close;",
    type: "source",
    version: 1,
  },
  { line: "22   title;footnote;ods _all_ close;", type: "source", version: 1 },
  { line: "23   ods graphics on;", type: "source", version: 1 },
  {
    line: "24   ods html5 style=Illuminate options(bitmap_mode='inline' svg_mode='inline');",
    type: "source",
    version: 1,
  },
  {
    line: "NOTE: Writing HTML5 Body file: sashtml2.htm",
    type: "note",
    version: 1,
  },
  {
    line: "25   %let _SASPROGRAMFILE = %nrquote(%nrstr(c:\\\\SAS\\\\GIT\\\\GitHub\\\\TestData\\\\error4.sas));",
    type: "source",
    version: 1,
  },
  { line: "26   proc foo; run;", type: "source", version: 1 },
  { line: "ERROR: Procedure FOO not found.", type: "error", version: 1 },
  { line: "", type: "note", version: 1 },
  {
    line: "NOTE: The SAS System stopped processing this step because of errors.",
    type: "note",
    version: 1,
  },
  {
    line: "NOTE: PROCEDURE FOO used (Total process time):",
    type: "note",
    version: 1,
  },
  { line: "      real time           0.00 seconds", type: "note", version: 1 },
  { line: "      cpu time            0.00 seconds", type: "note", version: 1 },
  { line: "      ", type: "note", version: 1 },
  { line: "27   ", type: "source", version: 1 },
  { line: "28   options option=foo;", type: "source", version: 1 },
  { line: "             ------", type: "error", version: 1 },
  { line: "             13", type: "error", version: 1 },
  {
    line: "ERROR 13-12: Unrecognized SAS option name OPTION.",
    type: "error",
    version: 1,
  },
  { line: "29   ", type: "source", version: 1 },
  { line: "", type: "note", version: 1 },
  { line: "", type: "note", version: 1 },
  { line: "30   data x;", type: "source", version: 1 },
  { line: "31   ", type: "source", version: 1 },
  { line: "32       print(x);", type: "source", version: 1 },
  { line: "                 -", type: "error", version: 1 },
  { line: "                 22", type: "error", version: 1 },
  { line: "                 76", type: "error", version: 1 },
  {
    line: "ERROR: Undeclared array referenced: print.",
    type: "error",
    version: 1,
  },
  {
    line: "ERROR 22-322: Syntax error, expecting one of the following: +, =.  ",
    type: "error",
    version: 1,
  },
  { line: "", type: "normal", version: 1 },
  {
    line: "ERROR 76-322: Syntax error, statement will be ignored.",
    type: "error",
    version: 1,
  },
  { line: "", type: "normal", version: 1 },
  {
    line: "3                                                          The SAS System                       Monday, January 22, 2024 05:24:00 AM",
    type: "title",
    version: 1,
  },
  { line: "", type: "title", version: 1 },
  { line: "33   ", type: "source", version: 1 },
  { line: "34   run;", type: "source", version: 1 },
  { line: "", type: "note", version: 1 },
  {
    line: "NOTE: The SAS System stopped processing this step because of errors.",
    type: "note",
    version: 1,
  },
  {
    line: "WARNING: The data set WORK.X may be incomplete.  When this step was stopped there were 0 observations and 1 variables.",
    type: "warning",
    version: 1,
  },
  {
    line: "WARNING: Data set WORK.X was not replaced because this step was stopped.",
    type: "warning",
    version: 1,
  },
  {
    line: "NOTE: DATA statement used (Total process time):",
    type: "note",
    version: 1,
  },
  { line: "      real time           0.00 seconds", type: "note", version: 1 },
  { line: "      cpu time            0.00 seconds", type: "note", version: 1 },
  { line: "      ", type: "note", version: 1 },
  { line: "", type: "note", version: 1 },
  {
    line: "35   ;*';*\\\";*/;run;quit;ods html5 close;",
    type: "source",
    version: 1,
  },
];

export const logWithLongSourceCode: LogLine[] = [
  {
    line: "6    /** LOG_START_INDICATOR **/",
    type: "source",
    version: 1,
  },
  {
    line: "7    %let _SASPROGRAMFILE = ",
    type: "source",
    version: 1,
  },
  {
    line: "7  !                        %nrquote(%nrstr(c:\\SAS\\GIT\\GitHub\\TestData\\error7.sas));",
    type: "source",
    version: 1,
  },
  { line: "8    proc casutil;", type: "source", version: 1 },
  {
    line: "ERROR: A connection to the Cloud Analytic Services session could not be made.",
    type: "error",
    version: 1,
  },
  { line: "ERROR: An error has occurred.", type: "error", version: 1 },
  {
    line: '8  !               load data=SASHELP.BASEBALL outcaslib="CASUSER" casout="CASBALL"; run;',
    type: "source",
    version: 1,
  },
  { line: "ERROR: An error has occurred.", type: "error", version: 1 },
  { line: "", type: "note", version: 1 },
  { line: "9    ", type: "source", version: 1 },
  { line: "", type: "note", version: 1 },
];

export const logWithMultipleIndicatorInOneLine: LogLine[] = [
  { line: "36   /** LOG_START_INDICATOR **/", type: "source", version: 1 },
  {
    line: "37   %let _SASPROGRAMFILE = %nrquote(%nrstr(c:\\SAS\\GIT\\GitHub\\TestData\\errot9.sas));",
    type: "source",
    version: 1,
  },
  {
    line: "38   /* PROC PRINT DATA=SASHELP.CLASS;",
    type: "source",
    version: 1,
  },
  { line: "39   RUN;*/", type: "source", version: 1 },
  { line: "40   /*", type: "source", version: 1 },
  { line: "41   %MACRO NAME;", type: "source", version: 1 },
  { line: "42   %MEND; */", type: "source", version: 1 },
  { line: "43   ", type: "source", version: 1 },
  { line: "44   /* %macro name;", type: "source", version: 1 },
  { line: "45   %mend; */", type: "source", version: 1 },
  { line: "46   ", type: "source", version: 1 },
  { line: "47   data _null_;", type: "source", version: 1 },
  { line: "48       set one;", type: "source", version: 1 },
  {
    line: "ERROR: File WORK.ONE.DATA does not exist.",
    type: "error",
    version: 1,
  },
  {
    line: "49       call call symputx('mac', quote(strip(emple)));",
    type: "source",
    version: 1,
  },
  {
    line: "                   -------                            -",
    type: "error",
    version: 1,
  },
  {
    line: "                   22                                 79",
    type: "error",
    version: 1,
  },
  { line: "                   68", type: "error", version: 1 },
  { line: "              ----", type: "error", version: 1 },
  { line: "              251", type: "error", version: 1 },
  {
    line: "ERROR 22-322: Syntax error, expecting one of the following: (, ;.  ",
    type: "error",
    version: 1,
  },
  { line: "", type: "normal", version: 1 },
  { line: "ERROR 79-322: Expecting a ).", type: "error", version: 1 },
  { line: "", type: "normal", version: 1 },
  {
    line: "ERROR 68-185: The function SYMPUTX is unknown, or cannot be accessed.",
    type: "error",
    version: 1,
  },
  { line: "", type: "normal", version: 1 },
  {
    line: "ERROR 251-185: The subroutine CALL is unknown, or cannot be accessed. Check your spelling. ",
    type: "error",
    version: 1,
  },
  {
    line: "               Either it was not found in the path(s) of executable images, or there was incorrect or missing subroutine descriptor ",
    type: "error",
    version: 1,
  },
  { line: "               information.", type: "error", version: 1 },
  { line: "", type: "normal", version: 1 },
  {
    line: "50       call execute(%let list=&list &mac);",
    type: "source",
    version: 1,
  },
  {
    line: "WARNING: Apparent symbolic reference MAC not resolved.",
    type: "warning",
    version: 1,
  },
  {
    line: "WARNING: Apparent symbolic reference MAC not resolved.",
    type: "warning",
    version: 1,
  },
  { line: "51   run;", type: "source", version: 1 },
  { line: "        -", type: "error", version: 1 },
  { line: "        79", type: "error", version: 1 },
  { line: "", type: "note", version: 1 },
  { line: "ERROR 79-322: Expecting a ).", type: "error", version: 1 },
  { line: "", type: "normal", version: 1 },
];

export const multipleSameProblemIndexAtOneLine: LogLine[] = [
  {
    type: "title",
    line: "16                                                   The SAS System                         15:44 Friday, March 22, 2024",
  },
  { type: "source", line: "261        /** LOG_START_INDICATOR **/" },
  { type: "source", line: "262        title;footnote;ods _all_ close;" },
  { type: "source", line: "263        ods graphics on;" },
  {
    type: "source",
    line: "264        ods html5 style=Ignite options(bitmap_mode='inline' svg_mode='inline')",
  },
  {
    type: "source",
    line: '264      ! body=\\"574c9522-8068-4c99-aeb5-4137a53ae941.htm\\";',
  },
  {
    type: "note",
    line: "NOTE: Writing HTML5 Body file: 574c9522-8068-4c99-aeb5-4137a53ae941.htm",
  },
  {
    type: "source",
    line: "265        %let _SASPROGRAMFILE = %nrquote(%nrstr(c:\\\\SAS\\\\GIT\\\\GitHub\\\\TestData\\\\error_04.sas));",
  },
  { type: "source", line: "266         /*=========================*/" },
  { type: "source", line: "267         /* Pass-Through Sample 1  */" },
  { type: "source", line: "268         /*=========================*/" },
  { type: "source", line: "269        /* BLANK LINE*/" },
  {
    type: "source",
    line: "270        title 'Pass-Through Sample 1: Brief Data for All Invoices';",
  },
  { type: "source", line: "271        /* BLANK LINE*/" },
  { type: "source", line: "272        options linesize=120;" },
  { type: "source", line: "273        /* BLANK LINE*/" },
  { type: "source", line: "274        proc sql;" },
  { type: "source", line: "275        connect to &dbms as mydb (&CONNOPT);" },
  { type: "error", line: "                      _              _" },
  { type: "error", line: "                      22             79" },
  { type: "error", line: "                      200            200" },
  {
    type: "warning",
    line: "WARNING: Apparent symbolic reference DBMS not resolved.",
  },
  {
    type: "warning",
    line: "WARNING: Apparent symbolic reference CONNOPT not resolved.",
  },
  { type: "error", line: "ERROR 22-322: Expecting a name.  " },
  { type: "error", line: "ERROR 79-322: Expecting a )." },
  {
    type: "error",
    line: "ERROR 200-322: The symbol is not recognized and will be ignored.",
  },
  {
    type: "note",
    line: "NOTE: PROC SQL set option NOEXEC and will continue to check the syntax of statements.",
  },
  { type: "source", line: "276        %put %superq(sqlxmsg);" },
  {
    type: "error",
    line: "ERROR: A Connection to the mydb DBMS is not currently supported, or is not installed at your site.",
  },
  { type: "source", line: "277        /* BLANK LINE*/" },
  { type: "source", line: "278           select INVNUM, NAME, BILLEDON," },
  { type: "source", line: "279                  AMTINUS format=dollar20.2" },
  { type: "source", line: "280           from connection to mydb" },
  {
    type: "source",
    line: "281              (select INVNUM, BILLEDON, AMTINUS, NAME",
  },
  { type: "source", line: "282                  from SAMDAT9, SAMDAT11" },
  {
    type: "source",
    line: "283                  where SAMDAT9.BILLEDTO=SAMDAT11.CUSTOMER",
  },
  { type: "source", line: "284                  order by BILLEDON, INVNUM);" },
  { type: "error", line: "ERROR: The MYDB engine cannot be found." },
  {
    type: "error",
    line: "ERROR: A Connection to the mydb DBMS is not currently supported, or is not installed at your site.",
  },
  { type: "source", line: "285        %put %superq(sqlxmsg);" },
  {
    type: "error",
    line: "ERROR: A Connection to the mydb DBMS is not currently supported, or is not installed at your site.",
  },
  { type: "source", line: "286        /* BLANK LINE*/" },
  { type: "source", line: "287        disconnect from mydb;" },
  { type: "note", line: "NOTE: Statement not executed due to NOEXEC option." },
  { type: "source", line: "288        quit;" },
  {
    type: "note",
    line: "NOTE: The SAS System stopped processing this step because of errors.",
  },
  { type: "note", line: "NOTE: PROCEDURE SQL used (Total process time):" },
  { type: "note", line: "      real time           0.02 seconds" },
  { type: "note", line: "      cpu time            0.00 seconds" },
  { type: "note", line: "      " },
  { type: "source", line: "289        /* BLANK LINE*/" },
  { type: "source", line: "290        proc sql;" },
  {
    type: "title",
    line: "17                                                   The SAS System                         15:44 Friday, March 22, 2024",
  },
  { type: "source", line: "291        connect to &dbms as mydb (&CONNOPT);" },
  { type: "error", line: "                      _              _" },
  { type: "error", line: "                      22             79" },
  { type: "error", line: "                      200            200" },
  {
    type: "warning",
    line: "WARNING: Apparent symbolic reference DBMS not resolved.",
  },
  {
    type: "warning",
    line: "WARNING: Apparent symbolic reference CONNOPT not resolved.",
  },
  { type: "error", line: "ERROR 22-322: Expecting a name.  " },
  { type: "error", line: "ERROR 79-322: Expecting a )." },
  {
    type: "error",
    line: "ERROR 200-322: The symbol is not recognized and will be ignored.",
  },
  {
    type: "note",
    line: "NOTE: PROC SQL set option NOEXEC and will continue to check the syntax of statements.",
  },
  { type: "source", line: "292        %put %superq(sqlxmsg);" },
  {
    type: "error",
    line: "ERROR: A Connection to the mydb DBMS is not currently supported, or is not installed at your site.",
  },
  { type: "source", line: "293        /* BLANK LINE*/" },
  { type: "source", line: "294        create view samples.brief as" },
  { type: "source", line: "295           select INVNUM, NAME, BILLEDON," },
  { type: "source", line: "296                  AMTINUS format=dollar20.2" },
  { type: "source", line: "297           from connection to mydb" },
  {
    type: "source",
    line: "298              (select INVNUM, BILLEDON, AMTINUS, NAME",
  },
  { type: "source", line: "299                  from SAMDAT9, SAMDAT11" },
  {
    type: "source",
    line: "300                  where SAMDAT9.BILLEDTO=SAMDAT11.CUSTOMER);",
  },
  { type: "note", line: "NOTE: Statement not executed due to NOEXEC option." },
  { type: "source", line: "301        /* BLANK LINE*/" },
  { type: "source", line: "302        %put %superq(sqlxmsg);" },
  {
    type: "error",
    line: "ERROR: A Connection to the mydb DBMS is not currently supported, or is not installed at your site.",
  },
  { type: "source", line: "303        /* BLANK LINE*/" },
  { type: "source", line: "304        disconnect from mydb;" },
  { type: "note", line: "NOTE: Statement not executed due to NOEXEC option." },
  { type: "source", line: "305        /* BLANK LINE*/" },
  { type: "source", line: "306        options ls=120 label;" },
  { type: "source", line: "307        /* BLANK LINE*/" },
  { type: "source", line: "308        select * from samples.brief" },
  { type: "source", line: "309           order by BILLEDON, INVNUM;" },
  { type: "error", line: "ERROR: Libref SAMPLES is not assigned." },
  { type: "source", line: "310        /* BLANK LINE*/" },
  { type: "source", line: "311        quit;" },
  {
    type: "note",
    line: "NOTE: The SAS System stopped processing this step because of errors.",
  },
  { type: "note", line: "NOTE: PROCEDURE SQL used (Total process time):" },
  { type: "note", line: "      real time           0.00 seconds" },
  { type: "note", line: "      cpu time            0.00 seconds" },
  { type: "note", line: "      " },
  { type: "source", line: "312        /* BLANK LINE*/" },
  { type: "source", line: "313          /*=========================*/" },
  { type: "source", line: "314          /* Pass-Through Sample 2  */" },
  { type: "source", line: "315          /*=========================*/" },
  { type: "source", line: "316        /* BLANK LINE*/" },
  { type: "source", line: "317        options ls=120;" },
  { type: "source", line: "318        /* BLANK LINE*/" },
  {
    type: "source",
    line: "319        title 'Pass-Through Sample 2: Interns Who Are Family Members of Employees';",
  },
  { type: "source", line: "320        /* BLANK LINE*/" },
  { type: "source", line: "321        proc sql;" },
  { type: "source", line: "322        connect to &dbms as mydb (&CONNOPT);" },
  { type: "error", line: "                      _              _" },
  { type: "error", line: "                      22             79" },
  {
    type: "title",
    line: "18                                                   The SAS System                         15:44 Friday, March 22, 2024",
  },
  { type: "error", line: "                      200            200" },
  {
    type: "warning",
    line: "WARNING: Apparent symbolic reference DBMS not resolved.",
  },
  {
    type: "warning",
    line: "WARNING: Apparent symbolic reference CONNOPT not resolved.",
  },
  { type: "error", line: "ERROR 22-322: Expecting a name.  " },
  { type: "error", line: "ERROR 79-322: Expecting a )." },
  {
    type: "error",
    line: "ERROR 200-322: The symbol is not recognized and will be ignored.",
  },
  {
    type: "note",
    line: "NOTE: PROC SQL set option NOEXEC and will continue to check the syntax of statements.",
  },
  { type: "source", line: "323        %put %superq(sqlxmsg);" },
  {
    type: "error",
    line: "ERROR: A Connection to the mydb DBMS is not currently supported, or is not installed at your site.",
  },
  { type: "source", line: "324        /* BLANK LINE*/" },
  {
    type: "source",
    line: "325        select samdat13.LASTNAME, samdat13.FIRSTNAM,",
  },
  {
    type: "source",
    line: "326               samdat13.EMPID, samdat13.FAMILYID,",
  },
  { type: "source", line: "327               samdat13.GENDER, samdat13.DEPT," },
  { type: "source", line: "328               samdat13.HIREDATE" },
  { type: "source", line: "329           from connection to mydb" },
  {
    type: "source",
    line: "330              (select * from SAMDAT10) as query1, samples.samdat13",
  },
  {
    type: "source",
    line: "331           where query1.EMPID=samdat13.FAMILYID;",
  },
  { type: "error", line: "ERROR: The MYDB engine cannot be found." },
  {
    type: "error",
    line: "ERROR: A Connection to the mydb DBMS is not currently supported, or is not installed at your site.",
  },
  { type: "error", line: "ERROR: Libref SAMPLES is not assigned." },
  { type: "source", line: "332        /* BLANK LINE*/" },
  { type: "source", line: "333        %put %superq(sqlxmsg);" },
  {
    type: "error",
    line: "ERROR: A Connection to the mydb DBMS is not currently supported, or is not installed at your site.",
  },
  { type: "source", line: "334        /* BLANK LINE*/" },
  { type: "source", line: "335        disconnect from mydb;" },
  { type: "note", line: "NOTE: Statement not executed due to NOEXEC option." },
  { type: "source", line: "336        quit;" },
  {
    type: "note",
    line: "NOTE: The SAS System stopped processing this step because of errors.",
  },
  { type: "note", line: "NOTE: PROCEDURE SQL used (Total process time):" },
  { type: "note", line: "      real time           0.00 seconds" },
  { type: "note", line: "      cpu time            0.00 seconds" },
  { type: "note", line: "      " },
  { type: "source", line: "337        /* BLANK LINE*/" },
  { type: "source", line: "338        /* BLANK LINE*/" },
  { type: "source", line: "339         /*=========================*/" },
  { type: "source", line: "340         /* Pass-Through Sample 3  */" },
  { type: "source", line: "341         /*=========================*/" },
  { type: "source", line: "342        /* BLANK LINE*/" },
  { type: "source", line: "343        proc sql;" },
  { type: "source", line: "344        /* BLANK LINE*/" },
  { type: "source", line: "345           create view samples.allemp as" },
  { type: "source", line: "346             select * from mydblib.SAMDAT10;" },
  { type: "error", line: "ERROR: Libref SAMPLES is not assigned." },
  { type: "error", line: "ERROR: Create View failed." },
  {
    type: "note",
    line: "NOTE: PROC SQL set option NOEXEC and will continue to check the syntax of statements.",
  },
  { type: "source", line: "347        /* BLANK LINE*/" },
  { type: "source", line: "348        quit;" },
  {
    type: "note",
    line: "NOTE: The SAS System stopped processing this step because of errors.",
  },
  { type: "note", line: "NOTE: PROCEDURE SQL used (Total process time):" },
  { type: "note", line: "      real time           0.00 seconds" },
  { type: "note", line: "      cpu time            0.00 seconds" },
  { type: "note", line: "      " },
  { type: "source", line: "349        /* BLANK LINE*/" },
  {
    type: "title",
    line: "19                                                   The SAS System                         15:44 Friday, March 22, 2024",
  },
  { type: "source", line: "350        %let dept='ACC%';" },
  { type: "source", line: "351        /* BLANK LINE*/" },
  { type: "source", line: "352        proc sql stimer;" },
  { type: "note", line: "NOTE: SQL Statement used (Total process time):" },
  { type: "note", line: "      real time           0.00 seconds" },
  { type: "note", line: "      cpu time            0.00 seconds" },
  { type: "note", line: "      " },
  {
    type: "source",
    line: "353        title 'Pass-Through Sample 3: Employees Who Earn Below the Dept Average",
  },
  { type: "source", line: "354        Salary';" },
  {
    type: "warning",
    line: "WARNING: Apparent symbolic reference DBMS not resolved.",
  },
  {
    type: "warning",
    line: "WARNING: Apparent symbolic reference CONNOPT not resolved.",
  },
  { type: "source", line: "355        connect to &dbms (&CONNOPT);" },
  { type: "error", line: "                      _" },
  { type: "error", line: "                      22" },
  { type: "error", line: "                      200" },
  { type: "error", line: "ERROR 22-322: Expecting a name.  " },
  {
    type: "error",
    line: "ERROR 200-322: The symbol is not recognized and will be ignored.",
  },
  {
    type: "note",
    line: "NOTE: PROC SQL set option NOEXEC and will continue to check the syntax of statements.",
  },
  { type: "note", line: "NOTE: SQL Statement used (Total process time):" },
  { type: "note", line: "      real time           0.00 seconds" },
  { type: "note", line: "      cpu time            0.00 seconds" },
  { type: "note", line: "      " },
  { type: "source", line: "356        /* BLANK LINE*/" },
  { type: "source", line: "357        select EMPID, LASTNAME" },
  { type: "source", line: "358           from samples.allemp" },
  { type: "source", line: "359           where DEPT like &dept and SALARY <" },
  { type: "source", line: "360                 (select avg(SALARY)" },
  { type: "source", line: "361                     from connection to &dbms" },
  {
    type: "warning",
    line: "WARNING: Apparent symbolic reference DBMS not resolved.",
  },
  { type: "source", line: "361                     from connection to &dbms" },
  { type: "error", line: "                                           _" },
  { type: "error", line: "                                           22" },
  { type: "error", line: "ERROR 22-322: Expecting a name.  " },
  { type: "source", line: "361                     from connection to &dbms" },
  { type: "error", line: "                                           _" },
  { type: "error", line: "                                           76" },
  {
    type: "error",
    line: "ERROR 76-322: Syntax error, statement will be ignored.",
  },
  {
    type: "source",
    line: "362                        (select SALARY from SAMDAT10",
  },
  {
    type: "source",
    line: "363                            where DEPT like &dept));",
  },
  { type: "note", line: "NOTE: SQL Statement used (Total process time):" },
  { type: "note", line: "      real time           0.00 seconds" },
  { type: "note", line: "      cpu time            0.00 seconds" },
  { type: "note", line: "      " },
  { type: "source", line: "364        %put %superq(sqlxmsg);" },
  {
    type: "error",
    line: "ERROR: A Connection to the mydb DBMS is not currently supported, or is not installed at your site.",
  },
  { type: "source", line: "365        disconnect from &dbms;" },
  { type: "error", line: "                           _" },
  { type: "error", line: "                           22" },
  { type: "error", line: "                           200" },
  {
    type: "warning",
    line: "WARNING: Apparent symbolic reference DBMS not resolved.",
  },
  { type: "error", line: "ERROR 22-322: Expecting a name.  " },
  {
    type: "title",
    line: "20                                                   The SAS System                         15:44 Friday, March 22, 2024",
  },
  {
    type: "error",
    line: "ERROR 200-322: The symbol is not recognized and will be ignored.",
  },
  { type: "note", line: "NOTE: SQL Statement used (Total process time):" },
  { type: "note", line: "      real time           0.00 seconds" },
  { type: "note", line: "      cpu time            0.00 seconds" },
  { type: "note", line: "      " },
  { type: "source", line: "366        /* BLANK LINE*/" },
  { type: "source", line: "367        quit;" },
  {
    type: "note",
    line: "NOTE: The SAS System stopped processing this step because of errors.",
  },
  { type: "note", line: "NOTE: PROCEDURE SQL used (Total process time):" },
  { type: "note", line: "      real time           0.00 seconds" },
  { type: "note", line: "      cpu time            0.00 seconds" },
  { type: "note", line: "      " },
  { type: "source", line: "368        ;*';*\\\";*/;run;quit;ods html5 close;" },
  {
    type: "source",
    line: "369        %put --vscode-sas-extension-submit-end--;",
  },
];

export const case4: LogLine[] = [
  {
    type: "title",
    line: "11                                                   The SAS System                       15:30 Thursday, April 18, 2024",
  },
  { type: "source", line: "177        /** LOG_START_INDICATOR **/" },
  { type: "source", line: "178        title;footnote;ods _all_ close;" },
  { type: "source", line: "179        ods graphics on;" },
  {
    type: "source",
    line: "180        ods html5 style=Ignite options(bitmap_mode='inline' svg_mode='inline')",
  },
  {
    type: "source",
    line: '180      ! body=\\"38b4ac72-54cd-45d5-8f57-39931d8b55f5.htm\\";',
  },
  {
    type: "note",
    line: "NOTE: Writing HTML5 Body file: 38b4ac72-54cd-45d5-8f57-39931d8b55f5.htm",
  },
  {
    type: "source",
    line: "181        %let _SASPROGRAMFILE = %nrquote(%nrstr(c:\\\\SAS\\\\GIT\\\\GitHub\\\\TestData\\\\error_case_4.sas));",
  },
  {
    type: "source",
    line: '182        data CUSTOMERS (label=\\"Customer data for geocoding\\");',
  },
  {
    type: "source",
    line: "183           infiles datalines x dlm=# dlm=# dlm=## dlm=# dlm=# dlm=# dlm=# dlm=#;",
  },
  {
    type: "error",
    line: "              _______           _     _     _     __     _     _     _     _     _",
  },
  {
    type: "error",
    line: "              1                 23    24    24    24     24    24    24    24    24",
  },
  {
    type: "error",
    line: "                                      24    24    24     24    24    24    24    24",
  },
  {
    type: "warning",
    line: "WARNING 1-322: Assuming the symbol INFILE was misspelled as infiles.",
  },
  { type: "error", line: "ERROR 23-2: Invalid option name X." },
  { type: "error", line: "ERROR 24-322: Variable name is not valid." },
  { type: "error", line: "ERROR 24-2: Invalid value for the DLM option." },
  {
    type: "source",
    line: "184           length address $ 24 city $ 24 state $ 2;",
  },
  {
    type: "source",
    line: "185           input address   /* House number and street name */",
  },
  {
    type: "source",
    line: "186              zip          /* Customer ZIP code (numeric)  */",
  },
  {
    type: "source",
    line: "187              city         /* City name                    */",
  },
  {
    type: "source",
    line: "188              state        /* State abbreviation           */;",
  },
  {
    type: "source",
    line: "189           cust_ID = _n_;   /* Assign customer ID number    */",
  },
  { type: "source", line: "190        datalines;" },
  {
    type: "note",
    line: "NOTE: The SAS System stopped processing this step because of errors.",
  },
  {
    type: "warning",
    line: "WARNING: The data set WORK.CUSTOMERS may be incomplete.  When this step was stopped there were 0 observations and 5 ",
  },
  { type: "warning", line: "         variables." },
  {
    type: "warning",
    line: "WARNING: Data set WORK.CUSTOMERS was not replaced because this step was stopped.",
  },
  { type: "note", line: "NOTE: DATA statement used (Total process time):" },
  { type: "note", line: "      real time           0.03 seconds" },
  { type: "note", line: "      cpu time            0.00 seconds" },
  { type: "note", line: "      " },
  { type: "source", line: "192        ;" },
  { type: "source", line: "193        run;" },
  { type: "source", line: "194        ;*';*\\\";*/;run;quit;ods html5 close;" },
  {
    type: "source",
    line: "195        %put --vscode-sas-extension-submit-end--;",
  },
];

export const case5: LogLine[] = [
  {
    type: "title",
    line: "12                                                   The SAS System                       15:30 Thursday, April 18, 2024",
  },
  { type: "source", line: "196        /** LOG_START_INDICATOR **/" },
  { type: "source", line: "197        title;footnote;ods _all_ close;" },
  { type: "source", line: "198        ods graphics on;" },
  {
    type: "source",
    line: "199        ods html5 style=Ignite options(bitmap_mode='inline' svg_mode='inline')",
  },
  {
    type: "source",
    line: '199      ! body=\\"0677d731-e06b-434b-bf34-7389838b5f25.htm\\";',
  },
  {
    type: "note",
    line: "NOTE: Writing HTML5 Body file: 0677d731-e06b-434b-bf34-7389838b5f25.htm",
  },
  {
    type: "source",
    line: "200        %let _SASPROGRAMFILE = %nrquote(%nrstr(c:\\\\SAS\\\\GIT\\\\GitHub\\\\TestData\\\\error_case_5.sas));",
  },
  {
    type: "source",
    line: '201        proc sgscatter data=sashelp.iris(=(species=\\"Virginica\\"));',
  },
  {
    type: "error",
    line: "                                            _                     _",
  },
  {
    type: "error",
    line: "                                            22                    22",
  },
  {
    type: "error",
    line: "                                                                  200",
  },
  { type: "error", line: "ERROR 22-7: Invalid option name =." },
  {
    type: "error",
    line: "ERROR 22-322: Syntax error, expecting one of the following: ;, BACKCOLOR, DATA, DATACOLORS, DATACONTRASTCOLORS, ",
  },
  {
    type: "error",
    line: "              DATALINEPATTERNS, DATASYMBOLS, DATTRMAP, DESCRIPTION, NOOPAQUE, NOSUBPIXEL, OPAQUE, PAD, RATTRMAP, ",
  },
  {
    type: "error",
    line: "              SGANNO, SUBPIXEL, TMPLOUT, WALLCOLOR.  ",
  },
  {
    type: "error",
    line: "ERROR 200-322: The symbol is not recognized and will be ignored.",
  },
  {
    type: "source",
    line: '201      ! proc sgscatter data=sashelp.iris(=(species=\\"Virginica\\"));',
  },
  {
    type: "error",
    line: "                                              _______",
  },
  { type: "error", line: "                                              22" },
  { type: "error", line: "ERROR 22-7: Invalid option name SPECIES." },
  {
    type: "source",
    line: '202          title \\"Multi-Celled Spline Curve for Species Virginica\\";',
  },
  {
    type: "source",
    line: "203          plot (sepallength sepalwidth)*(petallength petalwidth)",
  },
  { type: "source", line: "204               / pbspline;" },
  { type: "source", line: "205        run;" },
  {
    type: "note",
    line: "NOTE: The SAS System stopped processing this step because of errors.",
  },
  {
    type: "note",
    line: "NOTE: PROCEDURE SGSCATTER used (Total process time):",
  },
  { type: "note", line: "      real time           0.01 seconds" },
  { type: "note", line: "      cpu time            0.00 seconds" },
  { type: "note", line: "      " },
  { type: "source", line: "206        title;" },
  { type: "source", line: "207        ;*';*\\\";*/;run;quit;ods html5 close;" },
  {
    type: "source",
    line: "208        %put --vscode-sas-extension-submit-end--;",
  },
];

export const case6: LogLine[] = [
  {
    type: "title",
    line: "13                                                   The SAS System                       15:30 Thursday, April 18, 2024",
  },
  { type: "source", line: "209        /** LOG_START_INDICATOR **/" },
  { type: "source", line: "210        title;footnote;ods _all_ close;" },
  { type: "source", line: "211        ods graphics on;" },
  {
    type: "source",
    line: "212        ods html5 style=Ignite options(bitmap_mode='inline' svg_mode='inline')",
  },
  {
    type: "source",
    line: '212      ! body=\\"39fc438c-e10b-4931-a6e4-1f34c082c876.htm\\";',
  },
  {
    type: "note",
    line: "NOTE: Writing HTML5 Body file: 39fc438c-e10b-4931-a6e4-1f34c082c876.htm",
  },
  {
    type: "source",
    line: "213        %let _SASPROGRAMFILE = %nrquote(%nrstr(c:\\\\SAS\\\\GIT\\\\GitHub\\\\TestData\\\\error_case_6.sas));",
  },
  { type: "note", line: "NOTE: PROCEDURE HPCLUS used (Total process time):" },
  { type: "note", line: "      real time           0.03 seconds" },
  { type: "note", line: "      cpu time            0.01 seconds" },
  { type: "note", line: "      " },
  {
    type: "note",
    line: "NOTE: The SAS System stopped processing this step because of errors.",
  },
  {
    type: "source",
    line: "214        proc hpclus data=sampsio.dmairis maxclusters=9",
  },
  {
    type: "source",
    line: "215                 NOC=ABCB=10 minclusters=2 align=PCA criterion=FIRSTPEAK);",
  },
  { type: "error", line: "                        _____" },
  { type: "error", line: "                        1   22" },
  { type: "error", line: "                            200" },
  {
    type: "warning",
    line: "WARNING 1-322: Assuming the symbol ABC was misspelled as ABCB.",
  },
  {
    type: "error",
    line: "ERROR 22-322: Syntax error, expecting one of the following: ;, (, DATA, DISTANCE, DISTANCEINT, DISTANCENOM, IMP, ",
  },
  {
    type: "error",
    line: "              IMPUTE, IMPUTEINT, IMPUTENOM, INSEED, INSTAT, MAXC, MAXCLUSTERS, MAXITER, NOC, NOPRINT, OUTITER, OUTSTAT, ",
  },
  { type: "error", line: "              SEED, STANDARDIZE, STOPCRITERION.  " },
  {
    type: "error",
    line: "ERROR 200-322: The symbol is not recognized and will be ignored.",
  },
  { type: "source", line: "216           input  sep: pet: ;" },
  { type: "source", line: "217           ods output ABCStats=ABCStats1;" },
  { type: "source", line: "218        run;" },
  { type: "source", line: "219        ;*';*\\\";*/;run;quit;ods html5 close;" },
  {
    type: "source",
    line: "220        %put --vscode-sas-extension-submit-end--;",
  },
];

export const case7_8: LogLine[] = [
  {
    type: "title",
    line: "14                                                   The SAS System                       15:30 Thursday, April 18, 2024",
  },
  { type: "source", line: "221        /** LOG_START_INDICATOR **/" },
  { type: "source", line: "222        title;footnote;ods _all_ close;" },
  { type: "source", line: "223        ods graphics on;" },
  {
    type: "source",
    line: "224        ods html5 style=Ignite options(bitmap_mode='inline' svg_mode='inline')",
  },
  {
    type: "source",
    line: '224      ! body=\\"61e33882-6d9c-4cf9-89bc-6be999155016.htm\\";',
  },
  {
    type: "note",
    line: "NOTE: Writing HTML5 Body file: 61e33882-6d9c-4cf9-89bc-6be999155016.htm",
  },
  {
    type: "source",
    line: "225        %let _SASPROGRAMFILE = %nrquote(%nrstr(c:\\\\SAS\\\\GIT\\\\GitHub\\\\TestData\\\\error_case_7_8.sas));",
  },
  { type: "source", line: "226         data a;" },
  { type: "source", line: "227              drop theta pi;" },
  { type: "source", line: "228              array c{4} c1-c4;" },
  { type: "source", line: "229              array s{3} s1-s3;" },
  { type: "source", line: "230              pi = arcos(-1);" },
  { type: "source", line: "231              do Habitat=1 to 4;" },
  { type: "source", line: "232                 do Month=1 to 12;" },
  { type: "source", line: "233                    theta = pi * Month / 4;" },
  {
    type: "source",
    line: "234                    do i=1 to 4; c{i} = cos(i*theta); end;",
  },
  {
    type: "source",
    line: "235                    do i=1 to 3; s{i} = sin(i*theta); end;",
  },
  { type: "source", line: "236                    output;" },
  { type: "source", line: "237                 end;" },
  { type: "source", line: "238              end;" },
  { type: "source", line: "239           run;" },
  {
    type: "note",
    line: "NOTE: The data set WORK.A has 48 observations and 10 variables.",
  },
  { type: "note", line: "NOTE: DATA statement used (Total process time):" },
  { type: "note", line: "      real time           0.02 seconds" },
  { type: "note", line: "      cpu time            0.00 seconds" },
  { type: "note", line: "      " },
  {
    type: "source",
    line: "240            Data set a contains the 48 candidate points and includes the four cosine variables (c1, c2, c3, and c4)",
  },
  {
    type: "error",
    line: "                    ___                __                                                          __",
  },
  {
    type: "error",
    line: "_                                                                                                                       ",
  },
  {
    type: "error",
    line: "____                                                                                                                    ",
  },
  {
    type: "error",
    line: "                    56                 22                                                          22",
  },
  {
    type: "error",
    line: "200                                                                                                  ",
  },
  {
    type: "error",
    line: "22                                                                                                   ",
  },
  { type: "error", line: "                                       200" },
  { type: "error", line: "200                                       " },
  {
    type: "error",
    line: "ERROR 56-185: SET is not allowed in the DATA statement when option DATASTMTCHK=COREKEYWORDS.  Check for a missing ",
  },
  {
    type: "error",
    line: "              semicolon in the DATA statement, or use DATASTMTCHK=NONE.",
  },
  {
    type: "error",
    line: "ERROR 22-322: Syntax error, expecting one of the following: a name, a quoted string, (, /, ;, _DATA_, _LAST_, _NULL_.  ",
  },
  { type: "error", line: "ERROR 22-7: Invalid option name C1." },
  {
    type: "error",
    line: "ERROR 200-322: The symbol is not recognized and will be ignored.",
  },
  {
    type: "source",
    line: "240      ! Data set a contains the 48 candidate points and includes the four cosine variables (c1, c2, c3, and c4) or",
  },
  {
    type: "source",
    line: "240      ! three sine variables (s1, s2, and s3). The following statements produce Output 13.1.1:",
  },
  { type: "error", line: "                                 __             _" },
  { type: "error", line: "                                 22             22" },
  { type: "error", line: "ERROR 22-7: Invalid option name S1." },
  {
    type: "error",
    line: "ERROR 22-322: Syntax error, expecting one of the following: a name, a quoted string, /, ;, _DATA_, _LAST_, _NULL_.  ",
  },
  { type: "source", line: "241        /* BLANK LINE*/" },
  { type: "source", line: "242        proc optex seed=193030034 data=a;" },
  {
    type: "title",
    line: "15                                                   The SAS System                       15:30 Thursday, April 18, 2024",
  },
  { type: "error", line: "                          _" },
  { type: "error", line: "                          22" },
  { type: "error", line: "                          200" },
  { type: "source", line: "243           class    Habitat;" },
  { type: "error", line: "              _____" },
  { type: "error", line: "              180" },
  {
    type: "source",
    line: "244           model    Habitat Month c1-c4 s1-s3 / noint;",
  },
  { type: "error", line: "              _____" },
  { type: "error", line: "              180" },
  { type: "source", line: "245           generate n=12;" },
  { type: "error", line: "              ________" },
  { type: "error", line: "              180" },
  {
    type: "error",
    line: "ERROR 22-322: Syntax error, expecting one of the following: a name, a quoted string, (, /, ;, _DATA_, _LAST_, _NULL_.  ",
  },
  {
    type: "error",
    line: "ERROR 200-322: The symbol is not recognized and will be ignored.",
  },
  {
    type: "error",
    line: "ERROR 180-322: Statement is not valid or it is used out of proper order.",
  },
  { type: "source", line: "246        run;" },
  {
    type: "note",
    line: "NOTE: The SAS System stopped processing this step because of errors.",
  },
  { type: "note", line: "NOTE: DATA statement used (Total process time):" },
  { type: "note", line: "      real time           0.00 seconds" },
  { type: "note", line: "      cpu time            0.00 seconds" },
  { type: "note", line: "      " },
  { type: "source", line: "247        ;*';*\\\";*/;run;quit;ods html5 close;" },
  {
    type: "source",
    line: "248        %put --vscode-sas-extension-submit-end--;",
  },
];

export const case9: LogLine[] = [
  { type: "source", line: "3             %put &=workDir;" },
  {
    type: "normal",
    line: "WORKDIR=C:\\\\Users\\\\scnjdl\\\\AppData\\\\Local\\\\Temp\\\\SAS Temporary Files\\\\_TD44188_SAS-3YR23T3_\\\\Prc2",
  },
  {
    type: "note",
    line: 'NOTE: The current working directory is now \\"C:\\\\Users\\\\scnjdl\\\\AppData\\\\Local\\\\Temp\\\\SAS Temporary Files\\\\_TD44188_SAS-3YR23T3_\\\\Prc2\\".',
  },
  {
    type: "source",
    line: '4             %let rc = %sysfunc(dlgcdir(\\"&workDir\\"));',
  },
  { type: "source", line: "5             run;" },
  {
    type: "title",
    line: "2                                                          The SAS System                             16:36 Thursday, April 25, 2024",
  },
  { type: "source", line: "6          /** LOG_START_INDICATOR **/" },
  { type: "source", line: "7          title;footnote;ods _all_ close;" },
  { type: "source", line: "8          ods graphics on;" },
  {
    type: "source",
    line: '9          ods html5(id=vscode) path=\\"C:\\\\Users\\\\scnjdl\\\\AppData\\\\Local\\\\Temp\\\\SAS Temporary Files\\\\_TD44188_SAS-3YR23T3_\\\\Prc2\\"',
  },
  {
    type: "source",
    line: "9        ! style=Ignite options(bitmap_mode='inline' svg_mode='inline') body=\\\"375c94f5-9bbe-4abf-9381-6db8a336303b.htm\\\";",
  },
  {
    type: "note",
    line: "NOTE: Writing HTML5(VSCODE) Body file: 375c94f5-9bbe-4abf-9381-6db8a336303b.htm",
  },
  {
    type: "source",
    line: "10         %let _SASPROGRAMFILE = %nrquote(%nrstr(c:\\\\SAS\\\\GIT\\\\GitHub\\\\TestData\\\\error_case_9.sas));",
  },
  {
    type: "note",
    line: "NOTE: PROCEDURE MAPIMPORT used (Total process time):",
  },
  { type: "note", line: "      real time           0.00 seconds" },
  { type: "note", line: "      cpu time            0.00 seconds" },
  { type: "note", line: "      " },
  {
    type: "warning",
    line: "WARNING: Physical file does not exist, C:\\\\Users\\\\scnjdl\\\\AppData\\\\Local\\\\Temp\\\\SAS Temporary ",
  },
  {
    type: "warning",
    line: "         Files\\\\_TD44188_SAS-3YR23T3_\\\\Prc2\\\\~sasdemo\\\\data\\\\mapping\\\\states.shp.",
  },
  { type: "error", line: "ERROR: Unable to open DATAFILE." },
  {
    type: "note",
    line: "NOTE: The SAS System stopped processing this step because of errors.",
  },
  { type: "source", line: "11         PROC MAPIMPORT OUT=mystates" },
  {
    type: "source",
    line: '12         DATAFILE=\\"~sasdemo/data/mapping/states.shp\\";',
  },
  {
    type: "source",
    line: "13              SELECT STATE_FIPS STATE_NAME STATE_ABBR;",
  },
  {
    type: "source",
    line: "14              RENAME STATE_FIPS=FIPS STATE_NAME=STATE STATE_ABBR=ABBREV;",
  },
  { type: "source", line: "15         run;" },
  {
    type: "source",
    line: "16         ;*';*\\\";*/;run;quit;ods html5(id=vscode) close;",
  },
  {
    type: "source",
    line: "17         %put --vscode-sas-extension-submit-end--;",
  },
];

export const case10: LogLine[] = [
  {
    type: "title",
    line: "3                                                          The SAS System                             16:36 Thursday, April 25, 2024",
  },
  { type: "source", line: "18         /** LOG_START_INDICATOR **/" },
  { type: "source", line: "19         title;footnote;ods _all_ close;" },
  { type: "source", line: "20         ods graphics on;" },
  {
    type: "source",
    line: '21         ods html5(id=vscode) path=\\"C:\\\\Users\\\\scnjdl\\\\AppData\\\\Local\\\\Temp\\\\SAS Temporary Files\\\\_TD44188_SAS-3YR23T3_\\\\Prc2\\"',
  },
  {
    type: "source",
    line: "21       ! style=Ignite options(bitmap_mode='inline' svg_mode='inline') body=\\\"c43d6fcb-bc82-48e8-8d73-253845af2055.htm\\\";",
  },
  {
    type: "note",
    line: "NOTE: Writing HTML5(VSCODE) Body file: c43d6fcb-bc82-48e8-8d73-253845af2055.htm",
  },
  {
    type: "source",
    line: "22         %let _SASPROGRAMFILE = %nrquote(%nrstr(c:\\\\SAS\\\\GIT\\\\GitHub\\\\TestData\\\\error_case_10.sas));",
  },
  {
    type: "source",
    line: "23         proc sgplot data=&dvttestdata1 dattrmap=&dvttestdata2;",
  },
  { type: "error", line: "                            _" },
  { type: "error", line: "                            22" },
  { type: "error", line: "                            200" },
  {
    type: "warning",
    line: "WARNING: Apparent symbolic reference DVTTESTDATA1 not resolved.",
  },
  {
    type: "source",
    line: "23         proc sgplot data=&dvttestdata1 dattrmap=&dvttestdata2;",
  },
  {
    type: "error",
    line: "                                                   _",
  },
  {
    type: "error",
    line: "                                                   22",
  },
  { type: "error", line: "ERROR 22-322: Expecting a name.  " },
  {
    type: "error",
    line: "ERROR 200-322: The symbol is not recognized and will be ignored.",
  },
  {
    type: "source",
    line: "23         proc sgplot data=&dvttestdata1 dattrmap=&dvttestdata2;",
  },
  {
    type: "error",
    line: "                                                   _",
  },
  {
    type: "error",
    line: "                                                   200",
  },
  {
    type: "error",
    line: "ERROR 200-322: The symbol is not recognized and will be ignored.",
  },
  { type: "error", line: "ERROR: File WORK.DVTTESTDATA1.DATA does not exist." },
  {
    type: "warning",
    line: "WARNING: Apparent symbolic reference DVTTESTDATA2 not resolved.",
  },
  { type: "error", line: "ERROR: File WORK.DVTTESTDATA2.DATA does not exist." },
  {
    type: "source",
    line: "24             scatter x=x y=x2 / group=y3 attrid=myid1;",
  },
  { type: "error", line: "ERROR: No data set open to look up variables." },
  { type: "error", line: "ERROR: No data set open to look up variables." },
  { type: "error", line: "ERROR: No data set open to look up variables." },
  { type: "source", line: "25         run;" },
  {
    type: "note",
    line: "NOTE: The SAS System stopped processing this step because of errors.",
  },
  { type: "note", line: "NOTE: PROCEDURE SGPLOT used (Total process time):" },
  { type: "note", line: "      real time           0.04 seconds" },
  { type: "note", line: "      cpu time            0.00 seconds" },
  { type: "note", line: "      " },
  {
    type: "source",
    line: "26         ;*';*\\\";*/;run;quit;ods html5(id=vscode) close;",
  },
  {
    type: "source",
    line: "27         %put --vscode-sas-extension-submit-end--;",
  },
];

export const case11: LogLine[] = [
  {
    type: "title",
    line: "4                                                          The SAS System                             16:36 Thursday, April 25, 2024",
  },
  { type: "source", line: "28         /** LOG_START_INDICATOR **/" },
  { type: "source", line: "29         title;footnote;ods _all_ close;" },
  { type: "source", line: "30         ods graphics on;" },
  {
    type: "source",
    line: '31         ods html5(id=vscode) path=\\"C:\\\\Users\\\\scnjdl\\\\AppData\\\\Local\\\\Temp\\\\SAS Temporary Files\\\\_TD44188_SAS-3YR23T3_\\\\Prc2\\"',
  },
  {
    type: "source",
    line: "31       ! style=Ignite options(bitmap_mode='inline' svg_mode='inline') body=\\\"71b79405-8be6-4a49-9d5a-c1107c6b4c1d.htm\\\";",
  },
  {
    type: "note",
    line: "NOTE: Writing HTML5(VSCODE) Body file: 71b79405-8be6-4a49-9d5a-c1107c6b4c1d.htm",
  },
  {
    type: "source",
    line: "32         %let _SASPROGRAMFILE = %nrquote(%nrstr(c:\\\\SAS\\\\GIT\\\\GitHub\\\\TestData\\\\error_case_11.sas));",
  },
  { type: "source", line: "33         data hernio;" },
  {
    type: "source",
    line: "34            input patient age gender$ OKstatus leave los;",
  },
  { type: "source", line: "35            datalines;" },
  {
    type: "note",
    line: "NOTE: The data set WORK.HERNIO has 32 observations and 6 variables.",
  },
  { type: "note", line: "NOTE: DATA statement used (Total process time):" },
  { type: "note", line: "      real time           0.04 seconds" },
  { type: "note", line: "      cpu time            0.00 seconds" },
  { type: "note", line: "      " },
  { type: "source", line: "68         ;" },
  { type: "source", line: "69         /* BLANK LINE*/" },
  { type: "source", line: "70         data hernio_uv;" },
  { type: "source", line: "71            length dist $7;" },
  { type: "source", line: "72            set hernio;" },
  { type: "source", line: "73            response = (leave=1);" },
  { type: "source", line: '74            dist     = \\"Binary\\";' },
  { type: "source", line: "75            output;" },
  { type: "source", line: "76            response = los;" },
  { type: "source", line: '77            dist     = \\"Poisson\\";' },
  { type: "source", line: "78            output;" },
  {
    type: "source",
    line: "79            keep patient age OKstatus response dist;",
  },
  { type: "source", line: "80         run;" },
  {
    type: "note",
    line: "NOTE: There were 32 observations read from the data set WORK.HERNIO.",
  },
  {
    type: "note",
    line: "NOTE: The data set WORK.HERNIO_UV has 64 observations and 5 variables.",
  },
  { type: "note", line: "NOTE: DATA statement used (Total process time):" },
  { type: "note", line: "      real time           0.03 seconds" },
  { type: "note", line: "      cpu time            0.00 seconds" },
  { type: "note", line: "      " },
  { type: "source", line: "81         /* BLANK LINE*/" },
  {
    type: "source",
    line: '82         proc glimmix data=hernio_uv(where=(dist=\\"Binary));',
  },
  {
    type: "source",
    line: "83            model response(event='1') = age OKStatus / s dist=binary;",
  },
  { type: "note", line: "NOTE: PROCEDURE GLIMMIX used (Total process time):" },
  { type: "note", line: "      real time           0.13 seconds" },
  { type: "note", line: "      cpu time            0.00 seconds" },
  { type: "note", line: "      " },
  { type: "error", line: "ERROR: Syntax error while parsing WHERE clause." },
  {
    type: "note",
    line: "NOTE: The SAS System stopped processing this step because of errors.",
  },
  { type: "source", line: "84         run;" },
  { type: "source", line: "85         /* BLANK LINE*/" },
  { type: "source", line: "86         /* BLANK LINE*/" },
  {
    type: "source",
    line: "87         ;*';*\\\";*/;run;quit;ods html5(id=vscode) close;",
  },
  { type: "error", line: "                 _" },
  { type: "error", line: "                 79" },
  { type: "error", line: "                 22" },
  { type: "error", line: "                 180" },
  { type: "error", line: "ERROR 79-322: Expecting a )." },
  {
    type: "title",
    line: "5                                                          The SAS System                             16:36 Thursday, April 25, 2024",
  },
  {
    type: "error",
    line: "ERROR 22-322: Missing ')' parenthesis for data set option list",
  },
  {
    type: "error",
    line: "ERROR 180-322: Statement is not valid or it is used out of proper order.",
  },
  {
    type: "source",
    line: "88         %put --vscode-sas-extension-submit-end--;",
  },
];
