// Copyright © 2024, SAS Institute Inc., Cary, NC, USA.  All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0
import { LogLine } from "../../../src/connection";

export const logWith13Problems: LogLine[] = [
  { line: "29   title;footnote;ods _all_ close;", type: "source", version: 1 },
  { line: "30   ods graphics on;", type: "source", version: 1 },
  {
    line: "31   ods html5 style=Illuminate options(bitmap_mode='inline' svg_mode='inline');",
    type: "source",
    version: 1,
  },
  {
    line: "NOTE: Writing HTML5 Body file: sashtml2.htm",
    type: "note",
    version: 1,
  },
  {
    line: "32   %let _SASPROGRAMFILE = %nrquote(%nrstr(c:\\\\SAS\\\\GIT\\\\GitHub\\\\TestData\\\\error3.sas));",
    type: "source",
    version: 1,
  },
  { line: "33   ", type: "source", version: 1 },
  { line: "34   ", type: "source", version: 1 },
  { line: "35   ", type: "source", version: 1 },
  { line: "36   /* I am comment */", type: "source", version: 1 },
  { line: "37   options ls=72;", type: "source", version: 1 },
  { line: "38   data pf70 pm70 pf80 pm80;", type: "source", version: 1 },
  {
    line: "39   \\tinput state $ pop_f70 pop_m70 pop_f80 pop_m80 @@;",
    type: "source",
    version: 1,
  },
  {
    line: "40   \\tdrop pop_m70 pop_f70 pop_m80 pop_f80;",
    type: "source",
    version: 1,
  },
  { line: "41   \\tdecade= 70;", type: "source", version: 1 },
  { line: "42   \\tsex= 'Female'", type: "source", version: 1 },
  { line: "43   \\tpop= pop_f70;  output pf70;", type: "source", version: 1 },
  { line: "      ---", type: "error", version: 1 },
  { line: "      22", type: "error", version: 1 },
  {
    line: "ERROR 22-322: Syntax error, expecting one of the following: !, !!, &, ",
    type: "error",
    version: 1,
  },
  {
    line: "              *, **, +, -, /, ;, <, <=, <>, =, >, ><, >=, AND, EQ, GE, ",
    type: "error",
    version: 1,
  },
  {
    line: "              GT, IN, LE, LT, MAX, MIN, NE, NG, NL, NOTIN, OR, ^=, |, ",
    type: "error",
    version: 1,
  },
  { line: "              ||, ~=.  ", type: "error", version: 1 },
  { line: "", type: "normal", version: 1 },
  { line: "44   \\tsex= 'Male';", type: "source", version: 1 },
  { line: "45   \\tpop= pop_m70;  output pm70;", type: "source", version: 1 },
  { line: "46   \\tdecade= 80;", type: "source", version: 1 },
  { line: "47   \\tpop= pop_m80;  output pm80;", type: "source", version: 1 },
  { line: "48   \\tsex= 'Female';", type: "source", version: 1 },
  { line: "49   \\tpop= pop_f80;  output pf80;", type: "source", version: 1 },
  { line: "50   \\tcards,", type: "source", version: 1 },
  { line: "           -", type: "error", version: 1 },
  { line: "           22", type: "error", version: 1 },
  { line: "           76", type: "error", version: 1 },
  {
    line: "ERROR 22-322: Syntax error, expecting one of the following: ;, CANCEL, ",
    type: "error",
    version: 1,
  },
  { line: "              PGM.  ", type: "error", version: 1 },
  { line: "", type: "normal", version: 1 },
  {
    line: "ERROR 76-322: Syntax error, statement will be ignored.",
    type: "error",
    version: 1,
  },
  { line: "", type: "normal", version: 1 },
  {
    line: "51   ALA    1.78  1.66  2.02  1.87   ALASKA 0.14  0.16  0.19  0.21",
    type: "source",
    version: 1,
  },
  {
    line: "52   ARIZ   0.90  0.87  1.38  1.34   ARK    0.99  0.93  1.18  1.10",
    type: "source",
    version: 1,
  },
  {
    line: "53   CALIF 10.14  9.82 12.00 11.67   COLO   1.12  1.09  1.46  1.43",
    type: "source",
    version: 1,
  },
  {
    line: "54   CONN   1.56  1.47  1.61  1.50   DEL    0.28  0.27  0.31  0.29",
    type: "source",
    version: 1,
  },
  {
    line: "55   FLA    3.51  3.28  5.07  4.68   GA     2.36  2.23  2.82  2.64",
    type: "source",
    version: 1,
  },
  {
    line: "56   HAW    0.37  0.40  0.47  0.49   IDAHO  0.36  0.36  0.47  0.47",
    type: "source",
    version: 1,
  },
  {
    line: "57   ILL    5.72  5.39  5.89  5.54   IND    2.66  2.53  2.82  2.67",
    type: "source",
    version: 1,
  },
  {
    line: "58   IOWA   1.45  1.37  1.50  1.41   KAN    1.15  1.02  1.21  1.16",
    type: "source",
    version: 1,
  },
  {
    line: "59   KY     1.64  1.58  1.87  1.79   LA     1.87  1.77  2.17  2.04",
    type: "source",
    version: 1,
  },
  {
    line: "60   ME     0.51  0.48  0.58  0.55   MD     2.01  1.92  2.17  2.04",
    type: "source",
    version: 1,
  },
  {
    line: "61   MASS   2.97  2.72  3.01  2.73   MICH   4.53  4.39  4.75  4.52",
    type: "source",
    version: 1,
  },
  {
    line: "62   MINN   1.94  1.86  2.08  2.00   MISS   1.14  1.07  1.31  1.21",
    type: "source",
    version: 1,
  },
  {
    line: "63   MO     2.42  2.26  2.55  2.37   MONT   0.35  0.35  0.39  0.39",
    type: "source",
    version: 1,
  },
  {
    line: "64   NEB    0.76  0.72  0.80  0.77   NEV    0.24  0.25  0.40  0.41",
    type: "source",
    version: 1,
  },
  {
    line: "65   NH     0.38  0.36  0.47  0.45   NJ     3.70  3.47  3.83  3.53",
    type: "source",
    version: 1,
  },
  {
    line: "4                            The SAS System",
    type: "title",
    version: 1,
  },
  {
    line: "                                    Friday, January 19, 2024 08:12:00 AM",
    type: "title",
    version: 1,
  },
  { line: "", type: "title", version: 1 },
  {
    line: "66   NM     0.52  0.50  0.66  0.64   NY     9.52  8.72  9.22  8.34",
    type: "source",
    version: 1,
  },
  {
    line: "67   NC     2.59  2.49  3.03  2.86   ND     0.31  0.31  0.32  0.33",
    type: "source",
    version: 1,
  },
  {
    line: "68   OHIO   5.49  5.16  5.58  5.22   OKLA   1.31  1.25  1.55  1.48",
    type: "source",
    version: 1,
  },
  {
    line: "69   ORE    1.07  1.02  1.34  1.30   PA     6.13  5.67  6.18  5.68",
    type: "source",
    version: 1,
  },
  {
    line: "70   RI     0.48  0.46  0.50  0.45   SC     1.32  1.27  1.60  1.52",
    type: "source",
    version: 1,
  },
  {
    line: "71   SD     0.34  0.33  0.35  0.34   TENN   2.03  1.90  2.37  2.22",
    type: "source",
    version: 1,
  },
  {
    line: "72   TEXAS  5.72  5.48  7.23  7.00   UTAH   0.54  0.52  0.74  0.72",
    type: "source",
    version: 1,
  },
  {
    line: "73   VT     0.23  0.22  0.26  0.25   VA     2.35  2.30  2.73  2.62",
    type: "source",
    version: 1,
  },
  {
    line: "NOTE: DATA statement used (Total process time):",
    type: "note",
    version: 1,
  },
  { line: "      real time           0.01 seconds", type: "note", version: 1 },
  { line: "      cpu time            0.02 seconds", type: "note", version: 1 },
  { line: "      ", type: "note", version: 1 },
  {
    line: "NOTE: Character values have been converted to numeric ",
    type: "note",
    version: 1,
  },
  {
    line: "      values at the places given by: (Line):(Column).",
    type: "note",
    version: 1,
  },
  { line: "      42:7   44:7   48:7   ", type: "note", version: 1 },
  {
    line: "NOTE: The SAS System stopped processing this step because of errors.",
    type: "note",
    version: 1,
  },
  {
    line: "WARNING: The data set WORK.PF70 may be incomplete.  When this step was ",
    type: "warning",
    version: 1,
  },
  {
    line: "         stopped there were 0 observations and 4 variables.",
    type: "warning",
    version: 1,
  },
  {
    line: "WARNING: The data set WORK.PM70 may be incomplete.  When this step was ",
    type: "warning",
    version: 1,
  },
  {
    line: "         stopped there were 0 observations and 4 variables.",
    type: "warning",
    version: 1,
  },
  {
    line: "WARNING: The data set WORK.PF80 may be incomplete.  When this step was ",
    type: "warning",
    version: 1,
  },
  {
    line: "         stopped there were 0 observations and 4 variables.",
    type: "warning",
    version: 1,
  },
  {
    line: "WARNING: The data set WORK.PM80 may be incomplete.  When this step was ",
    type: "warning",
    version: 1,
  },
  {
    line: "         stopped there were 0 observations and 4 variables.",
    type: "warning",
    version: 1,
  },
  {
    line: "74   WASH   1.72  1.69  2.08  2.05   W.VA   0.90  0.84  1.00  0.95",
    type: "source",
    version: 1,
  },
  {
    line: "75   WIS    2.25  2.17  2.40  2.31   WYO    0.16  0.17  0.23  0.24",
    type: "source",
    version: 1,
  },
  {
    line: "76   XX      .     .     .     .     YY      .     .     .     .",
    type: "source",
    version: 1,
  },
  { line: "77   ;", type: "source", version: 1 },
  { line: "", type: "note", version: 1 },
  { line: "", type: "note", version: 1 },
  { line: "78   data popstate;", type: "source", version: 1 },
  { line: "79   \\tset pf70 pm70 pf80 pm80;", type: "source", version: 1 },
  {
    line: "80   \\tlabel pop= 'Census Population In Millions';",
    type: "source",
    version: 1,
  },
  { line: "81   title 'The SAS System';", type: "source", version: 1 },
  { line: "", type: "note", version: 1 },
  {
    line: "NOTE: The data set WORK.POPSTATE has 0 observations and 4 variables.",
    type: "note",
    version: 1,
  },
  {
    line: "NOTE: DATA statement used (Total process time):",
    type: "note",
    version: 1,
  },
  { line: "      real time           0.00 seconds", type: "note", version: 1 },
  { line: "      cpu time            0.00 seconds", type: "note", version: 1 },
  { line: "      ", type: "note", version: 1 },
  { line: "", type: "note", version: 1 },
  {
    line: "82   proc univariate data=popstate freq plot normal;",
    type: "source",
    version: 1,
  },
  { line: "83   \\tvar2 pop;", type: "source", version: 1 },
  { line: "      ----", type: "warning", version: 1 },
  { line: "      1", type: "warning", version: 1 },
  {
    line: "WARNING 1-322: Assuming the symbol VAR was misspelled as var2.",
    type: "warning",
    version: 1,
  },
  { line: "84   \\tid state;", type: "source", version: 1 },
  { line: "85   \\tby decade sex;", type: "source", version: 1 },
  {
    line: "86   \\toutput out= univout mean= popnmean median= popn50",
    type: "source",
    version: 1,
  },
  {
    line: "87   \\t\\tpctlpre= pop_  pctlpts= 50, 95 to 100 by 2.5;",
    type: "source",
    version: 1,
  },
  { line: "", type: "note", version: 1 },
  {
    line: "NOTE: The data set WORK.UNIVOUT has 0 observations and 0 variables.",
    type: "note",
    version: 1,
  },
  {
    line: "NOTE: PROCEDURE UNIVARIATE used (Total process time):",
    type: "note",
    version: 1,
  },
  { line: "      real time           0.01 seconds", type: "note", version: 1 },
  { line: "      cpu time            0.00 seconds", type: "note", version: 1 },
  { line: "      ", type: "note", version: 1 },
  { line: "", type: "note", version: 1 },
  {
    line: "5                            The SAS System",
    type: "title",
    version: 1,
  },
  {
    line: "                                    Friday, January 19, 2024 08:12:00 AM",
    type: "title",
    version: 1,
  },
  { line: "", type: "title", version: 1 },
  { line: "88   proc print data= univout;", type: "source", version: 1 },
  {
    line: "89   \\ttitle 'Output Dataset From PROC UNIVARIATE';",
    type: "source",
    version: 1,
  },
  {
    line: "90   \\tformat popn50 pop_50 pop_95 pop_97_5 pop_100 best8.;",
    type: "source",
    version: 1,
  },
  {
    line: "WARNING: Variable POPN50 not found in data set WORK.UNIVOUT.",
    type: "warning",
    version: 1,
  },
  {
    line: "WARNING: Variable POP_50 not found in data set WORK.UNIVOUT.",
    type: "warning",
    version: 1,
  },
  {
    line: "WARNING: Variable POP_95 not found in data set WORK.UNIVOUT.",
    type: "warning",
    version: 1,
  },
  {
    line: "WARNING: Variable POP_97_5 not found in data set WORK.UNIVOUT.",
    type: "warning",
    version: 1,
  },
  {
    line: "WARNING: Variable POP_100 not found in data set WORK.UNIVOUT.",
    type: "warning",
    version: 1,
  },
  { line: "91   ", type: "source", version: 1 },
  { line: "92   ;*';*\\\";*/;run;", type: "source", version: 1 },
  { line: "", type: "note", version: 1 },
  {
    line: "NOTE: PROCEDURE PRINT used (Total process time):",
    type: "note",
    version: 1,
  },
  { line: "      real time           0.01 seconds", type: "note", version: 1 },
  { line: "      cpu time            0.00 seconds", type: "note", version: 1 },
  { line: "      ", type: "note", version: 1 },
  { line: "", type: "note", version: 1 },
  {
    line: "92 !               quit;ods html5 close;",
    type: "source",
    version: 1,
  },
];

export const logWith7Problems: LogLine[] = [
  { line: "29   title;footnote;ods _all_ close;", type: "source", version: 1 },
  { line: "30   ods graphics on;", type: "source", version: 1 },
  {
    line: "31   ods html5 style=Ignite options(bitmap_mode='inline' svg_mode='inline');",
    type: "source",
    version: 1,
  },
  {
    line: "NOTE: Writing HTML5 Body file: sashtml2.htm",
    type: "note",
    version: 1,
  },
  {
    line: "32   %let _SASPROGRAMFILE = %nrquote(%nrstr(c:\\\\SAS\\\\GIT\\\\GitHub\\\\TestData\\\\error4.sas));",
    type: "source",
    version: 1,
  },
  { line: "33   proc foo; run;", type: "source", version: 1 },
  { line: "ERROR: Procedure FOO not found.", type: "error", version: 1 },
  { line: "", type: "note", version: 1 },
  {
    line: "NOTE: The SAS System stopped processing this step because of errors.",
    type: "note",
    version: 1,
  },
  {
    line: "NOTE: PROCEDURE FOO used (Total process time):",
    type: "note",
    version: 1,
  },
  { line: "      real time           0.00 seconds", type: "note", version: 1 },
  { line: "      cpu time            0.00 seconds", type: "note", version: 1 },
  { line: "      ", type: "note", version: 1 },
  { line: "34   ", type: "source", version: 1 },
  { line: "35   options option=foo;", type: "source", version: 1 },
  { line: "             ------", type: "error", version: 1 },
  { line: "             13", type: "error", version: 1 },
  {
    line: "ERROR 13-12: Unrecognized SAS option name OPTION.",
    type: "error",
    version: 1,
  },
  { line: "36   ", type: "source", version: 1 },
  { line: "", type: "note", version: 1 },
  { line: "", type: "note", version: 1 },
  { line: "37   data x;", type: "source", version: 1 },
  { line: "38   ", type: "source", version: 1 },
  { line: "39       print(x);", type: "source", version: 1 },
  { line: "                 -", type: "error", version: 1 },
  { line: "                 22", type: "error", version: 1 },
  { line: "                 76", type: "error", version: 1 },
  {
    line: "ERROR: Undeclared array referenced: print.",
    type: "error",
    version: 1,
  },
  {
    line: "ERROR 22-322: Syntax error, expecting one of the following: +, =.  ",
    type: "error",
    version: 1,
  },
  { line: "", type: "normal", version: 1 },
  {
    line: "ERROR 76-322: Syntax error, statement will be ignored.",
    type: "error",
    version: 1,
  },
  { line: "", type: "normal", version: 1 },
  { line: "40   ", type: "source", version: 1 },
  { line: "41   run;", type: "source", version: 1 },
  { line: "", type: "note", version: 1 },
  {
    line: "NOTE: The SAS System stopped processing this step because of errors.",
    type: "note",
    version: 1,
  },
  {
    line: "WARNING: The data set WORK.X may be incomplete.  When this step was stopped there were 0 observations and 1 variables.",
    type: "warning",
    version: 1,
  },
  {
    line: "WARNING: Data set WORK.X was not replaced because this step was stopped.",
    type: "warning",
    version: 1,
  },
  {
    line: "NOTE: DATA statement used (Total process time):",
    type: "note",
    version: 1,
  },
  { line: "      real time           0.00 seconds", type: "note", version: 1 },
  { line: "      cpu time            0.00 seconds", type: "note", version: 1 },
  { line: "      ", type: "note", version: 1 },
  { line: "", type: "note", version: 1 },
  {
    line: "42   ;*';*\\\";*/;run;quit;ods html5 close;",
    type: "source",
    version: 1,
  },
];

export const logWith3Problems: LogLine[] = [
  {
    line: "1                                                          The SAS System                       Monday, January 22, 2024 02:43:00 AM",
    type: "title",
    version: 1,
  },
  { line: "", type: "title", version: 1 },
  {
    line: "NOTE: Copyright (c) 2016-2023 by SAS Institute Inc., Cary, NC, USA. ",
    type: "note",
    version: 1,
  },
  {
    line: "NOTE: SAS (r) Proprietary Software V.04.00 (TS M0 MBCS3170) ",
    type: "note",
    version: 1,
  },
  {
    line: "      Licensed to SCI-VA-VIYA4CD-LAX-RELEASE-TESTREADY, Site 70180938.",
    type: "note",
    version: 1,
  },
  {
    line: "NOTE: This session is executing on the Linux 4.18.0-425.3.1.el8.x86_64 (LIN X64) platform.",
    type: "note",
    version: 1,
  },
  { line: "", type: "normal", version: 1 },
  { line: "", type: "normal", version: 1 },
  { line: "", type: "normal", version: 1 },
  { line: "NOTE: Additional host information:", type: "note", version: 1 },
  { line: "", type: "note", version: 1 },
  {
    line: " Linux LIN X64 4.18.0-425.3.1.el8.x86_64 #1 SMP Wed Nov 9 20:13:27 UTC 2022 x86_64 Red Hat Enterprise Linux release 8.9 (Ootpa) ",
    type: "note",
    version: 1,
  },
  { line: "", type: "note", version: 1 },
  { line: "NOTE: SAS initialization used:", type: "note", version: 1 },
  { line: "      real time           0.04 seconds", type: "note", version: 1 },
  { line: "      cpu time            0.04 seconds", type: "note", version: 1 },
  { line: "      ", type: "note", version: 1 },
  { line: "", type: "note", version: 1 },
  {
    line: "NOTE: AUTOEXEC processing beginning; file is /opt/sas/viya/config/etc/compsrv/default/autoexec.sas.",
    type: "note",
    version: 1,
  },
  { line: "", type: "normal", version: 1 },
  { line: "", type: "note", version: 1 },
  {
    line: "NOTE: DATA statement used (Total process time):",
    type: "note",
    version: 1,
  },
  { line: "      real time           0.01 seconds", type: "note", version: 1 },
  { line: "      cpu time            0.02 seconds", type: "note", version: 1 },
  { line: "      ", type: "note", version: 1 },
  { line: "", type: "note", version: 1 },
  { line: "", type: "note", version: 1 },
  { line: "", type: "normal", version: 1 },
  { line: "NOTE: AUTOEXEC processing completed.", type: "note", version: 1 },
  { line: "", type: "note", version: 1 },
  { line: "", type: "note", version: 1 },
  {
    line: "NOTE: The LOCKDOWN option has been set. SAS is now in the lockdown state.",
    type: "note",
    version: 1,
  },
  { line: "", type: "note", version: 1 },
  {
    line: "NOTE: NOTE: The LOCKDOWN option has been set. SAS is now in the lockdown state.",
    type: "note",
    version: 1,
  },
  { line: "1    title;footnote;ods _all_ close;", type: "source", version: 1 },
  { line: "2    ods graphics on;", type: "source", version: 1 },
  {
    line: "3    ods html5 style=Illuminate options(bitmap_mode='inline' svg_mode='inline');",
    type: "source",
    version: 1,
  },
  {
    line: "NOTE: Writing HTML5 Body file: sashtml.htm",
    type: "note",
    version: 1,
  },
  {
    line: "4    %let _SASPROGRAMFILE = %nrquote(%nrstr(c:\\\\SAS\\\\GIT\\\\GitHub\\\\TestData\\\\error5.sas));",
    type: "source",
    version: 1,
  },
  { line: "5    option ls=72,", type: "source", version: 1 },
  { line: "                 -", type: "error", version: 1 },
  { line: "                 13", type: "error", version: 1 },
  {
    line: "ERROR 13-12: Unrecognized SAS option name ,.",
    type: "error",
    version: 1,
  },
  { line: "", type: "normal", version: 1 },
  { line: "6    ", type: "source", version: 1 },
  { line: "7    data pf70;", type: "source", version: 1 },
  { line: "     ----", type: "error", version: 1 },
  { line: "     13", type: "error", version: 1 },
  {
    line: "ERROR 13-12: Unrecognized SAS option name DATA.",
    type: "error",
    version: 1,
  },
  { line: "", type: "error", version: 1 },
  { line: "7  ! data pf70;", type: "source", version: 1 },
  { line: "          ----", type: "error", version: 1 },
  { line: "          13", type: "error", version: 1 },
  {
    line: "ERROR 13-12: Unrecognized SAS option name PF70.",
    type: "error",
    version: 1,
  },
  { line: "", type: "normal", version: 1 },
  {
    line: "8    ;*';*\\\";*/;run;quit;ods html5 close;",
    type: "source",
    version: 1,
  },
];

export const replayedLogWith7Problems: LogLine[] = [
  {
    line: "1                                                          The SAS System                       Monday, January 22, 2024 05:24:00 AM",
    type: "title",
    version: 1,
  },
  { line: "", type: "title", version: 1 },
  {
    line: "NOTE: Copyright (c) 2016-2023 by SAS Institute Inc., Cary, NC, USA. ",
    type: "note",
    version: 1,
  },
  {
    line: "NOTE: SAS (r) Proprietary Software V.04.00 (TS M0 MBCS3170) ",
    type: "note",
    version: 1,
  },
  {
    line: "      Licensed to SCI-VA-VIYA4CD-LAX-RELEASE-TESTREADY, Site 70180938.",
    type: "note",
    version: 1,
  },
  {
    line: "NOTE: This session is executing on the Linux 4.18.0-425.3.1.el8.x86_64 (LIN X64) platform.",
    type: "note",
    version: 1,
  },
  { line: "", type: "normal", version: 1 },
  { line: "", type: "normal", version: 1 },
  { line: "", type: "normal", version: 1 },
  { line: "NOTE: Additional host information:", type: "note", version: 1 },
  { line: "", type: "note", version: 1 },
  {
    line: " Linux LIN X64 4.18.0-425.3.1.el8.x86_64 #1 SMP Wed Nov 9 20:13:27 UTC 2022 x86_64 Red Hat Enterprise Linux release 8.9 (Ootpa) ",
    type: "note",
    version: 1,
  },
  { line: "", type: "note", version: 1 },
  { line: "NOTE: SAS initialization used:", type: "note", version: 1 },
  { line: "      real time           0.04 seconds", type: "note", version: 1 },
  { line: "      cpu time            0.03 seconds", type: "note", version: 1 },
  { line: "      ", type: "note", version: 1 },
  { line: "", type: "note", version: 1 },
  {
    line: "NOTE: AUTOEXEC processing beginning; file is /opt/sas/viya/config/etc/compsrv/default/autoexec.sas.",
    type: "note",
    version: 1,
  },
  { line: "", type: "normal", version: 1 },
  { line: "", type: "note", version: 1 },
  {
    line: "NOTE: DATA statement used (Total process time):",
    type: "note",
    version: 1,
  },
  { line: "      real time           0.01 seconds", type: "note", version: 1 },
  { line: "      cpu time            0.00 seconds", type: "note", version: 1 },
  { line: "      ", type: "note", version: 1 },
  { line: "", type: "note", version: 1 },
  { line: "", type: "note", version: 1 },
  { line: "", type: "normal", version: 1 },
  { line: "NOTE: AUTOEXEC processing completed.", type: "note", version: 1 },
  { line: "", type: "note", version: 1 },
  { line: "", type: "note", version: 1 },
  {
    line: "NOTE: The LOCKDOWN option has been set. SAS is now in the lockdown state.",
    type: "note",
    version: 1,
  },
  { line: "", type: "note", version: 1 },
  {
    line: "NOTE: NOTE: The LOCKDOWN option has been set. SAS is now in the lockdown state.",
    type: "note",
    version: 1,
  },
  { line: "1    title;footnote;ods _all_ close;", type: "source", version: 1 },
  { line: "2    ods graphics on;", type: "source", version: 1 },
  {
    line: "3    ods html5 style=Illuminate options(bitmap_mode='inline' svg_mode='inline');",
    type: "source",
    version: 1,
  },
  {
    line: "NOTE: Writing HTML5 Body file: sashtml.htm",
    type: "note",
    version: 1,
  },
  {
    line: "4    %let _SASPROGRAMFILE = %nrquote(%nrstr(c:\\\\SAS\\\\GIT\\\\GitHub\\\\TestData\\\\error4.sas));",
    type: "source",
    version: 1,
  },
  { line: "5    proc foo; run;", type: "source", version: 1 },
  { line: "ERROR: Procedure FOO not found.", type: "error", version: 1 },
  { line: "", type: "note", version: 1 },
  {
    line: "NOTE: The SAS System stopped processing this step because of errors.",
    type: "note",
    version: 1,
  },
  {
    line: "NOTE: Due to ERROR(s) above, SAS set option OBS=0, enabling syntax check mode. ",
    type: "note",
    version: 1,
  },
  {
    line: "      This prevents execution of subsequent data modification statements.",
    type: "note",
    version: 1,
  },
  {
    line: "NOTE: PROCEDURE FOO used (Total process time):",
    type: "note",
    version: 1,
  },
  { line: "      real time           0.00 seconds", type: "note", version: 1 },
  { line: "      cpu time            0.00 seconds", type: "note", version: 1 },
  { line: "      ", type: "note", version: 1 },
  { line: "6    ", type: "source", version: 1 },
  { line: "7    options option=foo;", type: "source", version: 1 },
  { line: "             ------", type: "error", version: 1 },
  { line: "             13", type: "error", version: 1 },
  {
    line: "ERROR 13-12: Unrecognized SAS option name OPTION.",
    type: "error",
    version: 1,
  },
  { line: "8    ", type: "source", version: 1 },
  { line: "", type: "note", version: 1 },
  { line: "", type: "note", version: 1 },
  { line: "9    data x;", type: "source", version: 1 },
  { line: "10   ", type: "source", version: 1 },
  { line: "11       print(x);", type: "source", version: 1 },
  {
    line: "2                                                          The SAS System                       Monday, January 22, 2024 05:24:00 AM",
    type: "title",
    version: 1,
  },
  { line: "", type: "title", version: 1 },
  { line: "                 -", type: "error", version: 1 },
  { line: "                 22", type: "error", version: 1 },
  { line: "                 76", type: "error", version: 1 },
  {
    line: "ERROR: Undeclared array referenced: print.",
    type: "error",
    version: 1,
  },
  {
    line: "ERROR 22-322: Syntax error, expecting one of the following: +, =.  ",
    type: "error",
    version: 1,
  },
  { line: "", type: "normal", version: 1 },
  {
    line: "ERROR 76-322: Syntax error, statement will be ignored.",
    type: "error",
    version: 1,
  },
  { line: "", type: "normal", version: 1 },
  { line: "12   ", type: "source", version: 1 },
  { line: "13   run;", type: "source", version: 1 },
  { line: "", type: "note", version: 1 },
  {
    line: "NOTE: The SAS System stopped processing this step because of errors.",
    type: "note",
    version: 1,
  },
  {
    line: "WARNING: The data set WORK.X may be incomplete.  When this step was stopped there were 0 observations and 1 variables.",
    type: "warning",
    version: 1,
  },
  {
    line: "NOTE: DATA statement used (Total process time):",
    type: "note",
    version: 1,
  },
  { line: "      real time           0.00 seconds", type: "note", version: 1 },
  { line: "      cpu time            0.02 seconds", type: "note", version: 1 },
  { line: "      ", type: "note", version: 1 },
  { line: "", type: "note", version: 1 },
  {
    line: "14   ;*';*\\\";*/;run;quit;ods html5 close;",
    type: "source",
    version: 1,
  },
  { line: "15   title;footnote;ods _all_ close;", type: "source", version: 1 },
  { line: "16   ods graphics on;", type: "source", version: 1 },
  {
    line: "17   ods html5 style=Illuminate options(bitmap_mode='inline' svg_mode='inline');",
    type: "source",
    version: 1,
  },
  {
    line: "NOTE: Writing HTML5 Body file: sashtml1.htm",
    type: "note",
    version: 1,
  },
  {
    line: "18   %let _SASPROGRAMFILE = %nrquote(%nrstr(c:\\\\SAS\\\\GIT\\\\GitHub\\\\TestData\\\\error4.sas));",
    type: "source",
    version: 1,
  },
  { line: "19   ;", type: "source", version: 1 },
  {
    line: "20   ;*';*\\\";*/;run;quit;ods html5 close;",
    type: "source",
    version: 1,
  },
  { line: "21   title;footnote;ods _all_ close;", type: "source", version: 1 },
  { line: "22   ods graphics on;", type: "source", version: 1 },
  {
    line: "23   ods html5 style=Illuminate options(bitmap_mode='inline' svg_mode='inline');",
    type: "source",
    version: 1,
  },
  {
    line: "NOTE: Writing HTML5 Body file: sashtml2.htm",
    type: "note",
    version: 1,
  },
  {
    line: "24   %let _SASPROGRAMFILE = %nrquote(%nrstr(c:\\\\SAS\\\\GIT\\\\GitHub\\\\TestData\\\\error4.sas));",
    type: "source",
    version: 1,
  },
  { line: "25   proc foo; run;", type: "source", version: 1 },
  { line: "ERROR: Procedure FOO not found.", type: "error", version: 1 },
  { line: "", type: "note", version: 1 },
  {
    line: "NOTE: The SAS System stopped processing this step because of errors.",
    type: "note",
    version: 1,
  },
  {
    line: "NOTE: PROCEDURE FOO used (Total process time):",
    type: "note",
    version: 1,
  },
  { line: "      real time           0.00 seconds", type: "note", version: 1 },
  { line: "      cpu time            0.00 seconds", type: "note", version: 1 },
  { line: "      ", type: "note", version: 1 },
  { line: "26   ", type: "source", version: 1 },
  { line: "27   options option=foo;", type: "source", version: 1 },
  { line: "             ------", type: "error", version: 1 },
  { line: "             13", type: "error", version: 1 },
  {
    line: "ERROR 13-12: Unrecognized SAS option name OPTION.",
    type: "error",
    version: 1,
  },
  { line: "28   ", type: "source", version: 1 },
  { line: "", type: "note", version: 1 },
  { line: "", type: "note", version: 1 },
  { line: "29   data x;", type: "source", version: 1 },
  { line: "30   ", type: "source", version: 1 },
  { line: "31       print(x);", type: "source", version: 1 },
  { line: "                 -", type: "error", version: 1 },
  { line: "                 22", type: "error", version: 1 },
  { line: "                 76", type: "error", version: 1 },
  {
    line: "ERROR: Undeclared array referenced: print.",
    type: "error",
    version: 1,
  },
  {
    line: "ERROR 22-322: Syntax error, expecting one of the following: +, =.  ",
    type: "error",
    version: 1,
  },
  { line: "", type: "normal", version: 1 },
  {
    line: "ERROR 76-322: Syntax error, statement will be ignored.",
    type: "error",
    version: 1,
  },
  { line: "", type: "normal", version: 1 },
  {
    line: "3                                                          The SAS System                       Monday, January 22, 2024 05:24:00 AM",
    type: "title",
    version: 1,
  },
  { line: "", type: "title", version: 1 },
  { line: "32   ", type: "source", version: 1 },
  { line: "33   run;", type: "source", version: 1 },
  { line: "", type: "note", version: 1 },
  {
    line: "NOTE: The SAS System stopped processing this step because of errors.",
    type: "note",
    version: 1,
  },
  {
    line: "WARNING: The data set WORK.X may be incomplete.  When this step was stopped there were 0 observations and 1 variables.",
    type: "warning",
    version: 1,
  },
  {
    line: "WARNING: Data set WORK.X was not replaced because this step was stopped.",
    type: "warning",
    version: 1,
  },
  {
    line: "NOTE: DATA statement used (Total process time):",
    type: "note",
    version: 1,
  },
  { line: "      real time           0.00 seconds", type: "note", version: 1 },
  { line: "      cpu time            0.00 seconds", type: "note", version: 1 },
  { line: "      ", type: "note", version: 1 },
  { line: "", type: "note", version: 1 },
  {
    line: "34   ;*';*\\\";*/;run;quit;ods html5 close;",
    type: "source",
    version: 1,
  },
];
