name: Package and Publish VSIX

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "npm"
      - run: npm ci
      - run: npx @vscode/vsce package
      - uses: actions/upload-artifact@v4
        with:
          path: ./*.vsix
          retention-days: 5

      - uses: johnnybenson/package-json-versioned-action@v1.0.9
        id: package-json
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: echo "vsixPath=sas-lsp-${{ steps.package-json.outputs.version }}.vsix" >> "$GITHUB_OUTPUT"
        id: vsixPath
        if: steps.package-json.outputs.has-updated == 'true'
      - run: npx @vscode/vsce publish -i ${{ steps.vsixPath.outputs.vsixPath }}
        if: steps.package-json.outputs.has-updated == 'true'
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
      - run: npx ovsx publish ${{ steps.vsixPath.outputs.vsixPath }} -p ${{ secrets.OVSX_PAT }}
        if: steps.package-json.outputs.has-updated == 'true'
      - run: |
          git tag -f v${{ steps.package-json.outputs.version }}
          git push -f origin v${{ steps.package-json.outputs.version }}
        if: steps.package-json.outputs.has-updated == 'true'
