# This workflow perform basic checks for a pull request

name: Pull Request Check

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version-file: ".nvmrc"
          cache: "npm"
      - run: npm ci
      - run: npm run format:check
      - run: npm run copyright:check
        if: github.repository == 'sassoftware/vscode-sas-extension'
      - run: xvfb-run -a npm run test
        if: runner.os == 'Linux' && github.repository == 'sassoftware/vscode-sas-extension'
      - run: npx @vscode/vsce package
        if: github.repository == 'sassoftware/vscode-sas-extension'
      - uses: actions/upload-artifact@v7
        if: github.repository == 'sassoftware/vscode-sas-extension'
        with:
          path: ./*.vsix
          retention-days: 5
