name: Testing Complete

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - labeled
      - unlabeled

jobs:
  testing-complete:
    name: Testing Complete
    runs-on: ubuntu-latest

    steps:
      - name: Verify testing-complete label
        env:
          LABELS: ${{ toJSON(github.event.pull_request.labels.*.name) }}
        run: |
          echo "PR labels: $LABELS"

          if jq -e --arg label "testing-complete" 'index($label) != null' <<< "$LABELS" > /dev/null; then
            echo "testing-complete label found."
          else
            echo "testing-complete label is missing."
            exit 1
          fi
